### ISSUE TITLE
Drop count field from "taxonomic" in metadata?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#107]
@jimcasaer has noted that the `count` field in `taxonomic` can be confusing:

https://github.com/tdwg/camtrap-dp/blob/2e9b391033a91dbd856c4506777a380d687b1ae1/camtrap-dp-profile.json#L55-L58

Is expresses the number of observations per species, but that can differ a lot lot sequence vs image based, whether age/sex/individual distinctions are made, etc. ... Even though it is a non-mandatory field, he suggest it would be better to drop it from the metadata altogether and have people looking at the data instead (where these counts can be very easily retrieved, but in context).

@kbubnicki and others, any opinion about this?

**Comment by niconoe** [comment]
I'm not experienced with camera traps, but agree with the principle: if some piece of information

- can be confusing
- can (over time) get out of sync with the data
- can easily be extracted from the data (in context)

I think it just should be dropped from the metadata. If this `count` is often needed by end-users, I'm in favor of nicely documenting (code examples?)  the "how to retrieve from data".

**Comment by kbubnicki** [comment]
I agree that this information can be easily extracted from the data tables. The idea behind this field was to provide some quick & dirty summary of datasets both for humans (can quickly check if given dataset contains enough observations of target species without the need for downloading and calculating these statistics manually) and machines (camtrap (meta)data catalogoues).

**Comment by peterdesmet** [comment]
Yeah, the problem I see is that there is no indication of how the counts are calculated. Are you ok with dropping it?

**Comment by kbubnicki** [comment]
Yes, I am ok with this

**Comment by peterdesmet** [comment]
@kbubnicki can you accept #117 (just assigned you as reviewer), which implements this change.

**Comment by kbubnicki** [comment]
Done!
