### ISSUE TITLE
Chapman Core Documentation

### ISSUE THREAD

**Issue by ben-norton** [tdwg/camtrap-dp#109]
Chapman Core Schema, Diagrams, and Documentation
Schema Documentation: https://docs.google.com/spreadsheets/d/1p9a0fijHEIIlkWYh4VyfZxZVtbt-fa8TBDhASuznUcY/edit?usp=sharing
Supporting Diagrams: https://docs.google.com/presentation/d/1gr3OMHW-RujKhefKEl8x5cnQ7YUJPyQt7_05luyD9vs/edit?usp=sharing
Schema: https://drive.google.com/file/d/1e-8uPws0NMihKJ7fUh1XJ1ftcQ7wuV7-/view?usp=sharing

**Comment by peterdesmet** [comment]
Thanks @ben-norton, will review when I get a chance. I already have one question, but will create a separate issue for that.

**Comment by ben-norton** [comment]
New Data Model Diagram. Google sheet revisions are in progress.
I'm going to map the relationship to frictionless using views.
![chapman_core_20210517_coreOnly](https://user-images.githubusercontent.com/7331520/118553985-062eac00-b72f-11eb-946c-c08898213446.png)

**Comment by ben-norton** [comment]
I'd like to keep this topic moving alongside Camtrap-DP. This may not be an immediate issue or topic of discussion, but it will circle back eventually. Whether it stays an issue is another question. I don't think its technically an 'issue' rather a topic accompaniment along with similar resources in a wiki. You could create a wiki page for past and current camera trap data models. Then this moves under that page as a subsection alongside WI and eMammal.

**Comment by ben-norton** [comment]
This is moving to a separate repository and should be removed.

**Comment by peterdesmet** [comment]
@ben-norton can I close this issue then?
