### ISSUE TITLE
Include taxon_id in observations

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#115]
It would be a better foreign key to the `taxonomic` scope than `scientific_name`.

**Comment by kbubnicki** [comment]
If this proposal is about adding `taxon_id` as an extra field and still keeping `scientific_name` than it makes sense to me.

**Comment by peterdesmet** [comment]
Yes, indeed, I would keep `scientific_name` around in `observations.csv`. As you suggest in https://github.com/tdwg/camtrap-dp/issues/108#issuecomment-853793533, `vernacular_name` could be dropped.
