### ISSUE TITLE
Should we call it `taxa` or `species` or `(sub)species`

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#120]
Camtrap observations are typically of species, but can also be of subspecies of higher classification levels. How should we call this in the standard?

- `species`: very recognizable, but technically not entirely correct
- `(sub)species`: a bit clucky, and doesn't cover higher classification levels
- `taxa`: technically correct, but maybe less recognizable

Examples:

> Table with observations based on the multimedia files. Associated with deployments (`deployment_id`), sequences (`sequence_id`) and optionally individual multimedia files (`multimedia_id`). Observations can mark non-animal events (camera setup, human, empty) or one or more animal observations (`observation_type` = `animal`) of a certain **?species**, count, age, sex, behaviour and/or individual.

```json
"?species": {
      "description": "",
      "type": "object",
      "required": [
        "taxon_id",
        "scientific_name"
      ],
      "properties": {
        "taxon_id": {
          "description": "Taxon ID of the ?species according to a taxonomic reference list defined by `taxon_id_reference`.",
          "type": "string",
          "format": "default"
        },
        "scientific_name": {
          "description": "Scientific name of the ?species.",
          "type": "string",
          "format": "default"
        },
        "vernacular_name": {
          "description": "Common name of the ?species, preferably in English.",
          "type": "string",
          "format": "default"
        }
      }
    }
```

**Comment by rondlg** [comment]
I'd say stick either with taxa or maybe scientificName to follow as is done elsewhere. Either of the others will definitely clash.

**Comment by peterdesmet** [comment]
Thanks @rondlg, I’ll opt for taxa then 👌

**Comment by peterdesmet** [comment]
Resolved in #121

**Comment by rondlg** [comment]
rank is the other piece of the puzzle.

**Comment by peterdesmet** [comment]
Yes, but I would not add this field. Camtrap DPs are required to have a taxonomic coverage, with `taxon_id`s from a reference system (e.g. GBIF backbone, Catalogue of Life). So all related info (rank, status, higher classification, etc.) can be derived from there. Also, given that camera traps mostly capture animals, it's luckily fairly easy to guess the rank from the scientific name.
