### ISSUE TITLE
Don't use `format: uri` for multimedia`file_path`

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#123]
Since multimedia can be local or remote paths, we should not use `format: uri`:

https://github.com/tdwg/camtrap-dp/blob/9d1d85a69f84435e2ad72ef0ef9f1de4f10d5f2a/multimedia-table-schema.json#L47-L49

 In Frictionless they solve the url-or-path with:

```
"type": "string",
"pattern": "^(?=^[^./~])(^((?!\\.{2}).)*$).*$",
```

@kbubnicki Maybe we should adopt the same?

**Comment by kbubnicki** [comment]
I think that at least theoretically we can keep `format: uri` as `uri` can also be specified as a relative path to a local resource; see e.g. 
https://www.w3.org/DesignIssues/Relative.html (by Tim Berners-Lee)

However, I am not sure if both cases (url or local path) are taken into account during validation. Have you already tested this @peterdesmet ?

**Comment by peterdesmet** [comment]
You are right, it validates for whatever content is in there 🤷‍♂️

**Comment by peterdesmet** [comment]
I spoke too soon, it does not validate on paths:

```
===  =====  ==========  ================================================================================================================
row  field  code        message                                                                                                         
===  =====  ==========  ================================================================================================================
  3      5  type-error  Type error in the cell "bird.jpg" in row "3" and field "file_path" at position "5": type is "string/uri"        
  4      5  type-error  Type error in the cell "no-such-file.jpg" in row "4" and field "file_path" at position "5": type is "string/uri"
  5      5  type-error  Type error in the cell "just text" in row "5" and field "file_path" at position "5": type is "string/uri"       
  6      5  type-error  Type error in the cell "no-link" in row "6" and field "file_path" at position "5": type is "string/uri"         
===  =====  ==========  ================================================================================================================
```

**Comment by kbubnicki** [comment]
Thanks for checking this! Then we should change it as you have already suggested i.e. `"pattern": "^(?=^[^./~])(^((?!\\.{2}).)*$).*$"`
