### ISSUE TITLE
Information withheld or data generalizations?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#135]
As mentioned in #133 we want to add a term to indicate _at dataset level_ **when/what data has been generalized/withheld**. Darwin Core has two terms for this (at record level):

- https://dwc.tdwg.org/terms/#dwc:informationWithheld: Additional information that exists, but that has not been shared in the given record.
- https://dwc.tdwg.org/terms/#dwc:dataGeneralizations: Actions taken to make the shared data less specific or complete than in its original form. Suggests that alternative data of higher quality may be available on request.

I'd rather have a single term to indicate this (e.g. as a short paragraph), should it be named:

- `information_withheld`
- `data_generalizations`
- `data_withheld_generalized`

Suggestions welcome.

**Comment by kbubnicki** [comment]
I would stay compatible with Darwin Core here. My choice would be `information_withheld`.

**Comment by peterdesmet** [comment]
@ben-norton @rondlg @kbubnicki thinking about this a bit more, I'm a bit hesitant to add another free-text field at dataset level. Is it not ok if the applied data generalizations/withheld information are described in the data package **description**/abstract? Note that in the IPT, there is no specific term for this either: people generally write it in the description or additional information. E.g.:

https://www.gbif.org/dataset/8a5cbaec-2839-4471-9e1d-98df301095dd#description:

> Generalized and/or withheld information: to prevent camera trap theft, coordinates are rounded to 3 decimals (111m).

**Comment by peterdesmet** [comment]
Discussed during meeting of July 8 and decided not to add an extra term for this.
