### ISSUE TITLE
Should contributors be required?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#138]
`contributors` is a non-required Frictionless Data Package property: https://specs.frictionlessdata.io/data-package/#contributors

Given that:

- All data packages will have at least one person involved
- It would be good to have at least one person to contact
- We make terms like spatial, temporal, taxonomic coverage required

I think we should make `contributors` a required property with at least one element.

The same could be argued about `organizations`, but personally I would keep that one optional.

@ben-norton @kbubnicki others thoughts?

**Comment by yliefting** [comment]
I agree with @peterdesmet , and also think we should make organization optional. We occasionally have enthusiasts run their own projects without being part of some organization.
