### ISSUE TITLE
Require a camtrap-dp to have specific resources

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#145]
I think the validation should check that a Camtrap DP has at least 3 resources, with the names `deployments`, `observations` and `multimedia`.

1. I think it should be possible have additional resources (e.g. Darwin Core views)
2. One could argue that it should be possible to publish a Camtrap DP without the multimedia, but that would currently break foreign keys. Thoughts?

**Comment by peterdesmet** [comment]
Note to self: this checks that there are **exactly** 3 resources with those names:

```
"resources": {
          "items": {
            "properties": {
              "name": {
                "enum": [
                  "deployments",
                  "multimedia",
                  "observations"
                ]
              }
            }
          }
        },
```

**Comment by kbubnicki** [comment]
Absolutely agree that all 3 tables should be checked if they are part of DP.

**Comment by peterdesmet** [comment]
Good. I've been looking into this and it's easy to require 3 resource with those names (basically: minItems: 3, enum). It is a lot harder to express _at least_ those 3 items, especially since Frictionless makes use of json schema draft 4, which does not have the `contains` keyword. So far I've not been able to find a way to express this. Help welcome. 😄

**Comment by peterdesmet** [comment]
With help from [Stackoverflow](https://stackoverflow.com/questions/68086511), this is a solution. Because we're in JSON schema draft 04 it is hard to read:

```json
        "resources": {
          "not": {
            "items": {
              "not": {
                "type": "object",
                "properties": {
                  "name": { "enum": ["deployments"] }
                },
                "required": ["name"]
              },
              "not": {
                "type": "object",
                "properties": {
                  "name": { "enum": ["multimedia"] }
                },
                "required": ["name"]
              },
              "not": {
                "type": "object",
                "properties": {
                  "name": { "enum": ["observations"] }
                },
                "required": ["name"]
              }
            }
          }
        }
```

And when testing, it did seem to let pass some things that it shouldn't.

I see 4 potential solutions:

- Try to figure how to make the testing more robust
- Use draft-06 JSON schema, which has the `contains` keywords, making a more readable schema. Not sure if we can mix draft-04 (Frictionless) and draft-06 (camtrap-dp)
- Convince Frictionless to use draft-06 or later
- Only allow 3 resources and no more.

**Comment by kbubnicki** [comment]
For the upcoming release 1.0 I would stay with the option:
 
>     * Only allow 3 resources and no more.

and wait for Frictionless switching to draft-06 or later.
