### ISSUE TITLE
Simplify vernacular names structure?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#147]
In #108 I suggested a new structure for taxonomic scope, so one could add more than one vernacular name per taxon:

```json
[
  {
    "taxon_id": 1,
    "scientific_name": "Homo sapiens",
    "vernacular_names": [
      {
        "name": "human",
        "language": "en"
      },
      {
        "name": "mens",
        "language": "nl"
      }
    ]
  },
  {
    "taxon_id": 2,
    "scientific_name": "Apes apes",
    "vernacular_names": [
      {
        "name": "gierzwaluw",
        "language": "nl"
      }
    ]
  },
  {
    "taxon_id": 3,
    "scientific_name": "Vulpes vulpes",
    "vernacular_names": [
      {
        "name": "fox",
        "language": "en"
      }
    ]
  }
]
```

I think this structure might be too complex:

1. it does allows for more than one vernacular name per language, which could be seen as a feature, but also adds complexity that I don't think is necessary for an exchange format
2. you have to loop over every vernacular name array per taxon to find name(s) for your language of interest (if it exists)

---

Maybe we can simplify this to `key = value` pairs for the vernacular names where `key` is the language code and value the scientific name, like so:

```json
[
  {
    "taxon_id": 1,
    "scientific_name": "Homo sapiens",
    "vernacular_names": {
      "nl": "mens",
      "en": "human"
    }
  },
  {
    "taxon_id": 2,
    "scientific_name": "Apes apes",
    "vernacular_names": {
      "nl": "gierzwaluw"
    }
  },
  {
    "taxon_id": 3,
    "scientific_name": "Vulpes vulpes",
    "vernacular_names": {
      "en": "fox"
    }
  }
]
```

This only allows for one name per language, but in my opinion it simplifies reading this data, because you don't have nested elements. E.g.:

```R
library(jsonlite)
> fromJSON("species.json")
  taxon_id scientific_name vernacular_names.nl vernacular_names.en
1        1    Homo sapiens                mens               human
2        2       Apes apes          gierzwaluw                <NA>
3        3   Vulpes vulpes                <NA>                 fox
```

@niconoe @damianooldoni I'm also interested to have your opinion on this. Is the current implementation (top) workable or would you also prefer the second one?

**Comment by damianooldoni** [comment]
@peterdesmet: indeed, allowing multiple vernacular names of the same languages will make it quite complicated to extract the info in a data.frame easily (I speak about R). In Python could be easier, but still it means adding one level of hierarchy and so making things more complicated for sure.

As far as I know typical camera trap applications show one vernacular name together with the scientific name, so simplifying things is welcome and will not break anything.
