### ISSUE TITLE
Rename "age" as "life_stage"

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#160]
The term "age" has a vocabulary of values that do not express age in years, but rather a lifestage.

https://github.com/tdwg/camtrap-dp/blob/88ac2d6905276f27f93ab5e4a7895ad413d9348b/observations-table-schema.json#L140-L155

I would therefore rename the term to `life_stage`, cf. Darwin Core. Thoughts?

**Comment by peterdesmet** [comment]
@ben-norton @kbubnicki ok with this change?

**Comment by ben-norton** [comment]
Excellent point. lifeStage is the correct term, especially given the association with Darwin Core and in the greater biodiversity data context. You could use relatuve_age, but that drops that cross reference with Darwin Core, which we should avoid wherever possible.

**Comment by peterdesmet** [comment]
Ok, will make a pull request to update this.
