### ISSUE TITLE
Observation vs classification vs identification vs annotation

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#164]
I'm still wondering if "observations" (see [table](https://tdwg.github.io/camtrap-dp/)) is the best term to use for annotations/observations/classifications/identifications. It is especially confusing when compared to Darwin Core/GBIF data, where observations means "observations of species". I think we've had this discussion before, but I can't find it in the issues. So, with this issue I want to open that discussion or at least document the decision.

## Observations

- Good: current situation. Conceptually, the animal observations _are_ Darwin Core observations
- Bad: does not only contain animal observations (but also blanks, vehicles, etc.) which makes it confusing with Darwin Core observations. Also, an animal recognized by a machine is to my knowledge not what is understood by a Darwin Core `MachineObservation`

Terms (current situation):

```
observations.csv
Table with observations based on the multimedia files.

observation_id
observation_type: animal/human/vehicle/empty/undefined/unclassified
classification_method: human/machine
classified_by
classification_timestamp
classification_confidence
```

## ~Classifications~

- Good: we already have terms `classified_by`, etc.
- Bad: can be easily confused with taxonomical classification

Terms (* indicates changes):

```
classifications.csv*
Table with classifications based on the multimedia files.*

classification_id*
classification_type*: animal/human/vehicle/empty/undefined/unclassified
classification_method: human/machine
classified_by
classification_timestamp
classification_confidence
```
## Identifications

- Good: ...
- Bad: I think this suffers the same problem as observations, as in that it is too close to Darwin Core _animal_ identifications. I'm also not sure if "identifications" are a term used for marking something as "blank"

Terms (* indicates changes):

```
identifications.csv*
Table with identifications based on the multimedia files.*

identification_id*
identification_type*: animal/human/vehicle/empty/undefined/unclassified
identification_method*: human/machine
identified_by*
identification_timestamp*
identification_confidence*
```

## Annotations

- Good: pretty broad term, so can apply to animal or blank annotations. Not used in Darwin Core.
- Bad: maybe the term is too broad?

Terms (* indicates changes):

```
annotations.csv*
Table with annotations based on the multimedia files.*

annotation_id*
annotation_type*: animal/human/vehicle/empty/undefined/unclassified
annotation_method*: human/machine
annotated_by*
annotation_timestamp*
annotation_confidence*
```

Feedback welcome (cc @jimcasaer @yliefting @ben-norton @timrobertson100 @kbubnicki @tucotuco)

**Comment by tucotuco** [comment]
If it helps, a dwc:MachineObservation is a record whose ultimate source was something recorded by a Machine, this includes camera-trap based records as well as records based on photos taken by a human. It would apply in all cases where dc:type is one of `StillImage`, `MovingImage`, `Sound`. It has nothing to do with intention.

**Comment by peterdesmet** [comment]
Classifications is out: too confusing

**Comment by timrobertson100** [comment]
I understand the dilemma, as the table is effectively mixing two distinct things 

1. metadata about how the image came to be (triggering, whether it was part of diagnostics etc) 
2. metadata about organisms detected on the image including behaviour, sex, life stage, species identification and how the identification was made (i.e. "classic" DwC Occurrence records)

I don't know if this is in scope, but I wonder if it makes sense to split this into separate tables of ImageAnnotations and SpeciesObservations? As a general rule, I favor tabular designs where each record is an instance of the same thing to avoid having overly general row types.

**Comment by peterdesmet** [comment]
@timrobertson100 triggering itself is now out, it will be part of media (#163), but diagnostics is not. **We could investigate if splitting those image vs species annotations helps our case (@ben-norton @kbubnicki)**. See #177

**Comment by timrobertson100** [comment]
If splitting doesn't fit the usage pattern (e.g. in the tools that will produce these) then I think I'd probably go with "observations" or "annotations". "identification" is something I'd consider narrower (i.e. only the species identification) than the rows actually contain.

**Comment by peterdesmet** [comment]
Yeah, identification also seems to imply that non-consensus identifications for the same animal are allowed, but I think we want to keep that out of scope. @kbubnicki @ben-norton agree?

**Comment by Tim-Hofmeester** [comment]
I think observation would work perfectly well for an empty image or observation of a vehicle, but I see the problem that Darwin Core/GBIF use it only for animals (and plants I assume). 

I think the idea of splitting it between annotations for the first step (what's on the image) and then observation only for animal annotations sounds like a good example, but only if it is easy to split the meta data between these two tables (and if it is easy to implement in existing workflows/software).

**Comment by kbubnicki** [comment]
I would stay with "observations".

As for the idea of  splitting -> https://github.com/tdwg/camtrap-dp/issues/177#issuecomment-981673734

> I think observation would work perfectly well for an empty image or observation of a vehicle, but I see the problem that Darwin Core/GBIF use it only for animals (and plants I assume).

But in the end only "observations" of animals will be exported to GBIF / converted to DC so maybe it is not a real problem?
