### ISSUE TITLE
Should observations be split in species and non-species observations?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#177]
See remark by @timrobertson100 at https://github.com/tdwg/camtrap-dp/issues/164#issuecomment-931406516

I think if we split, we should split hierarchically:

1. High level animal/vehicle/blank/human identification for each sequence/image (based on identification approach). 1-1 with sequences or images.
2. Species identifications related to animal identifications. M-1 with identifications of type animal

Some of the fields (classified_by etc.) would appear in both tables though. It also still assumes consensus identifications.

```
deployment -> images grouped in sequence -> annotation (singular) -> species observations (plural)
```

**Comment by kbubnicki** [comment]
I get the point by @timrobertson100 and of course it makes a lot of sense but I am against this change as it would introduce another layer of complexity (an extra table) and in my opinion this new structure would be more confusing for camera trapping data producers & users.
