### ISSUE TITLE
`unknown` lifeStage and sex

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#212]
Why do we have the value `unknown` for lifeStage and sex? What is the recommendation for using this vs not providing a value?

**Comment by peterdesmet** [comment]
I think we should remove "unknown". If you don't know, then leave it blank. Unless there's a scenario where someone would want to know all of the "unknowns". This may be overly audacious, but if you don't know something, then it's probably not fit for reuse and shouldn't be published.

_Originally posted by @ben-norton in https://github.com/tdwg/camtrap-dp/issues/213#issuecomment-1221534459_

**Comment by jimcasaer** [comment]
I would prefer that it stays in. It makes clear that the observer did look at the age / sex category but was not able to determine the age class or sex. For the analysis this is different from on observation where the observer only determined the species and did not bother to look at age or sex and therefore left this open @peterdesmet

**Comment by tucotuco** [comment]
One option that is used in controlled vocabularies of observations like
this is to make all explicit options available, for example, "assessed,
unknown" and "not assessed".

**Comment by peterdesmet** [comment]
Since there is **no guarantee** observers marked "assessed, but unknown" as `unknown` or that systems don't export unassessed values as `unknown`, the values `unknown` and `NULL` are very easily conflated. In the analysis, they would be considered the same. I would avoid this confusing for data publishers and users and remove `unknown` as a value (cf. how we don't have it in e.g. `featureType`)

**Comment by ben-norton** [comment]
I fully support for this decision.
