### ISSUE TITLE
Rename `classificationConfidence` to `classificationProbability`

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#217]
`classificationConfidence` currently has the definition:

> Accuracy confidence of the classification. Expressed as a probability, with 1 being maximum confidence. Provide an approximate value for human classifications.

In #208 @danstowell wants to make the clarification that the field is usually not intended for human classifications, which lead to the [suggestion](https://github.com/tdwg/camtrap-dp/pull/208#issuecomment-1092988173) by @ben-norton that the field should be a probability rather than confidence:

> Computer vision models return a vector of probabilities for every object a model has been trained to classify. You can set a reporting threshold (e.g., only results > 80%) to omit most of them. You end up with 4 or 5. If an expert confirms the top result, that leaves 1. The term 'estimated probability' is not an concise representation, nor is the term confidence. It's the probability, measured by a machine, that the model accurately classified the species in an image. I would suggest classifierProbability or something similar.

See also @danstowell's comment at https://github.com/tdwg/camtrap-dp/issues/170#issuecomment-1092526487:

> Both of these are covered well if confidences are expressed as probabilities. I appreciate that it's hard to get true probabilities from manual (human) annotations, and that there are other approaches (e.g. categorical or rank-based).
> 
> In my humblest opinion: (a) manual annotations should typically not come with confidences expressed as probabilities (unless they've actually been estimated by some procedure), but merely with attribution of which person/project/institution did the annotation; (b) AI-derived annotations should be strongly encouraged to include confidences expressed as probabilities.

**Comment by kbubnicki** [comment]
I agree it is a good proposal to rename this attribute.
