### ISSUE TITLE
Remove `food` from baitUse vocab

### ISSUE THREAD

**Issue by ben-norton** [tdwg/camtrap-dp#220]
Two issues to consider revising in the baitUse controlled vocabulary (split into two issues if needed).
First, I think the sensory-based approach is the right strategy. These issues are mainly associated with a departure from this strategy.

The term 'food' in baitUse should be removed for two main reasons:
1. The term meaning overlaps with several "sensory" based terms, especially scent. Terms in a domain with meanings that overlap should be avoided and all values should be equal in granularity. 
2. The meaning of the term 'food' is a narrower than the sensory terms. All terms in a controlled vocabulary should be equal granularity.

The term 'other' should be removed or the parent term should be revised.
One of the four main principles for creating controlled vocabularies is the elimination of ambiguity (ANSI/NISO Z39.19-2005). 'Other' is a commonly appended term to controlled vocabularies. The merit is clear. However, ambiguity in any form detracts from the primary functions of a controlled vocabulary (see ANSI/NISO Z39.19-2005). There are exceptions to the use of 'other', but I don't think this is one.

**Comment by kbubnicki** [comment]
@ben-norton this definition was taken directly from WI documentation ;) But I get your point and agree about removing terms `food` and `other`.

Maybe still useful to discuss how one can provide more details about bait used. using `comments` field?

**Comment by peterdesmet** [comment]
Yes, we can refer to `comments` field. We already do for other fields too.

**Comment by peterdesmet** [comment]
I have created a separate issue for `other`, since it also applies to `featureType`, see #22.

**Comment by peterdesmet** [comment]
We were already deviating from WI by changing `meat` to `food`. I agree it deviates from the sensory bait categories:

```
none
scent
visual
acoustic
food <-- odd category
```

But is it always possible to translate `food/meat` to one of the sensory values? I'd like to get input from @jimcasaer @Tim-Hofmeester @yliefting etc.
