### ISSUE TITLE
Deployment Groups

### ISSUE THREAD

**Issue by ben-norton** [tdwg/camtrap-dp#222]
The session and array deployment group fields have merit, but I think there's a better way to handle them. 
1. If there isn't a way to define the purpose of a deployment group, then the separation between array and session has little meaning. They should just be combined into a general field for grouping deployments. It does allow for a one-to-two relationship in a flat structure (a one-to-many restricted to two), but I there may be better ways to handle this. Currently, arrays and sessions are identifier fields with a little context.
2. Semantically the terms arrays and sessions have wider implications and can risk misinterpretation. They are both types of deployment groups. There is very little ambiguity in the phrase 'deployment group'. Deployment groups have a purpose and type. If this many-to-many isn't possible given the data package structure, then at minimum the terms should be re-evaluated and reorganized to allow a purpose or criteria field. 
3. The term 'array' is a term already in use in camera trapping for a variety of purposes. Re-purposing it here for a specific purpose risks mistaken identity. In other words, there may be a bias or pre-existing familiarity that may be hard to shake for some providers.

**Comment by peterdesmet** [comment]
@ben-norton what is your suggestion to fix this. Have a single term `deploymentGroup` where users can add IDs (plural) on how to group deployments (without context)?

**Comment by peterdesmet** [comment]
Hi Ben, see #227 for discussion on this topic. Closing this issue.
