### ISSUE TITLE
None and Unknown

### ISSUE THREAD

**Issue by ben-norton** [tdwg/camtrap-dp#223]
What is the logic behind the widespread usage of the terms 'none' and 'unknown'? Maybe I'm missing something here. None and unknown are usually best represented by null in a distributed dataset. A provider might use None and unknown to keep track of records that have undergone review and those that have not.  The purpose of these terms ('none', 'unknown', and 'n/a') is to support internal workflows. Once data is published, that purpose is no longer relevant. Therefore, they should be dropped when a dataset is published. Null implies not known. If a provider knows, then they would enter a value.

**Comment by peterdesmet** [comment]
For reference, `none` is currently used for [baitUse](https://tdwg.github.io/camtrap-dp/data/#deployments.baituse) and [featureType](https://tdwg.github.io/camtrap-dp/data/#deployments.featuretype), `unknown` is currently used in [sex](https://tdwg.github.io/camtrap-dp/data/#observations.sex), [lifeStage](https://tdwg.github.io/camtrap-dp/data/#observations.lifestage) and [observationType](https://tdwg.github.io/camtrap-dp/data/#observations.observationtype). Whether we should have `unknown` in sex and lifeStage is discussed in #212.

Imo, for bait, I think there is a big difference between:
- "I know there was no bait" (none)
- "I don't know whether there was bait" (unknown/null)

For featureType, I agree that `none` is more problematic. Do featureless deployments exist? Does `none` mean that none of the listed featureTypes applies or would that be `other`?

So I'm fine removing `none` from featureType, but not `baitUse`. And to lump `unknown` and `null` (with preference for `null`), but see #212 for that topic.

**Comment by kbubnicki** [comment]
Assuming #212 is already solved, I would say remove `none` from `featureType` but keep it for `baitUse`
