### ISSUE TITLE
Rename `session` -> `temporalGroup`, `array` -> `spatialGroup` and allow multiple values

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#227]
In a conversation with @ben-norton it came up that it would be good to rename:

- [session](https://tdwg.github.io/camtrap-dp/data/#deployments.session) -> `temporalGroup`
- [array](https://tdwg.github.io/camtrap-dp/data/#deployments.array) -> `spatialGroup`

"temporal"  and "spatial" are already mentioned in the definitions, but it's probably good to name the terms as such as well. Especially "array" is a very specific type of spatial deployment group.

In addition - just like tags - we could suggest to allow multiple values separated by `|`. I'm not sure if we should then also pluralize the names to `temporalGroup`, `spatialGroup`.

Another approach would be to have the general term `deploymentGroup`(s) and describe those deployment groups (temporal, spatial, definition) in a separate table or metadata.

**Comment by kbubnicki** [comment]
I think that renaming both fields is a good idea and the proposed names are rather self-explaining. If agreed then also #222 can be closed I think.

**Comment by ben-norton** [comment]
What about deployment groups that are not temporal or spatial (thematic)? For example, deployments that are grouped into single and paired configurations or grouped based on cardinal direction.

**Comment by peterdesmet** [comment]
@ben-norton I would say that those currently (v1.0) don’t have a dedicated field, but can be expressed in the `tags` fields.

**Comment by peterdesmet** [comment]
I have opted to allow `|` separated values, but to keep the term name singular:

- `temporalGroup`: Temporal deployment group(s), formatted as a pipe (`|`) separated list. Can be used for sessions, seasons, months, years, etc. Deployment groups without temporal/spatial context can be provided in `tags`.
- `spatialGroup`: Spatial deployment group(s), formatted as a pipe (`|`) separated list. Can be used for arrays, grids, clusters, etc. Deployment groups without temporal/spatial context can be provided in `tags`.

**Comment by peterdesmet** [comment]
Discussed with @kbubnicki. As there is currently no strong demand for `spatialGroup` and `temporalGroup` (they were introduced in the very first idea of Camtrap DP), we think it better to go with @ben-norton suggestion and have `deploymentGroup`. There one can provide `key:value` pairs. We also think it better to separate this term from `tags`. Will include this in a PR.

**Comment by peterdesmet** [comment]
Updated to `deploymentGroup` (right above `tags`) in 27302fe:

![Image](https://user-images.githubusercontent.com/600993/195847909-f20ee311-a1e6-49f8-8221-1f16d7c55175.png)

**Comment by peterdesmet** [comment]
Reopening, I think we should pluralize the term name to `deploymentGroups`, cf. tags.

**Comment by ben-norton** [comment]
100% agree with the conclusion and implementation.
