### ISSUE TITLE
Add `kingdom`, `phylum`, `class` as none required properties to taxa in taxonomic coverage

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#228]
_Based on a conversation with @ben-norton_

Users of a Camtrap DP can filter observations out of the box on `scientificName`. If they (or software) joins the observation with info in taxonomic coverage, they can also filter on vernacular name and rank (e.g. give me all observations identified at species level).

But you can't filter on "give me all observations that are Aves (identified at any level)". For that you rely a service that can match your `scientificName` to a backbone (e.g. GBIF) or that can match your `taxonID` to a service, which might or might not be available for the `taxonIDReference` you used.

The data management system from which Camtrap DP is derived however, often has more taxon information available, but it currently cannot be expressed in Camtrap DP. We suggest to allow including that information, by adding the following "classic" higher classification terms to taxa in taxonomic scope:

- kingdom
- phylum
- class
- order
- family
- subfamily
- genus

These terms (just like `taxonRank` and `vernacularNames`) would not be required. But if provided, they help the user in doing queries like "give me all Aves".

A full record would look like this:

```json
{
  "taxonID": "32FH",
  "taxonIDReference": "https://www.catalogueoflife.org",
  "scientificName": "Ardea",
  "taxonRank": "genus",
  "kingdom": "Animalia",
  "phylum": "Chordata",
  "class": "Aves",
  "order": "Pelecaniformes",
  "family": "Ardeidae",
  "subfamily": "Ardeinae",
  "genus": "Ardea",
  "vernacularNames": {
    "en": "great herons",
    "nl": "reigers"
  }
},

**Comment by tucotuco** [comment]
I support this, but if you intend to use terms from Darwin Core for these, please substitute genericName for genus.

**Comment by tucotuco** [comment]
Retracted my comment about genericName for genus. This is the classification information, not the generic part of the scientificName.

**Comment by tucotuco** [comment]
I maintain my support for the proposal.

**Comment by peterdesmet** [comment]
All: should we include `subfamily`? It is a Darwin Core term, but it is not one of the classical ranks (e.g. GBIF does not use it). Does it occur often that camera trap observations are identified at subfamily level? Or that users want to group observations by subfamily? Agouti does not store subfamily information. Wildlife Insights doesn't either I believe.

@ben-norton @jimcasaer @yliefting any feedback on this?

Note: one can argue that `kingdom` or even `phylum` should not be included, because camtrap observations are (always?) of vertebrates only. I would add those ranks for completeness (and the potential to identify plants if need be).

**Comment by peterdesmet** [comment]
Decided to exclude `subfamily` as it is not one of the classic ranks (supported by GBIF).

**Comment by ben-norton** [comment]
What happens when it's added to Darwin Core and GBIF? I don't forsee a scenario where that doesn't happen.

**Comment by peterdesmet** [comment]
If it is added, we can support it. It currently isn't exported by Agouti or Wildlife Insights.
