### ISSUE TITLE
Add `coordinatePrecision` property to metadata

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#230]
See https://github.com/inbo/camtraptor/issues/147, also discussed with @tucotuco.

This property would allow to indicate at package level to what extend coordinates have been fuzzied (e.g. to protect sensitive species or prevent theft of active cameras). The term is borrowed from Darwin Core (https://dwc.tdwg.org/terms/#dwc:coordinatePrecision).

Especially for sensitive species, it would of course be better if specific coordinates could be fuzzied (rather than project wide), so that the non-sensitive data retains the highest precision, however:

1. A project wide setting is something publishers are much more likely to provide, since specific fuzzying needs to be done carefully i.e. you have to be careful to fuzzy the coordinates for _all deployments_ at the location where the sensitive species was observed.
2. Setting a project wide coordinate precision does not prevent publishers to _still_ provide more precise coordinates and a smaller `coordinateUncertainty` for specific (non-sensitive) deployments in the data.

Most of all, the project wide `coordinatePrecision` communicates up front what a user can expect in the dataset.

**Comment by kbubnicki** [comment]
I agree it would be a useful extra attribute

**Comment by peterdesmet** [comment]
@tucotuco, is this definition ok (see 3d42c11)

> Minimum precision of the `longitude` and `latitude` of the deployments (e.g. `0.001` for a minimum precision of 0.001 degree). Especially relevant when coordinates have been rounded to protect sensitive species.

**Comment by tucotuco** [comment]
Sorry for the delay. I think "minimum precision" might be too vague or even
misleading since the minimum number would be the greatest precision. What
about, "The least precise of the coordinate precisions for the longitudes
 and latitudes of the deployments (e.g., 0.001 for a precision of 0.001
degree). Especially relevant when coordinates have been rounded to protect
sensitive species."

**Comment by peterdesmet** [comment]
Thanks, rephrased in 24e435b to:

> Least precise coordinate precision of the `deployments.latitude` and `deployments.longitude` (e.g. `0.01` for coordinates with a precision of 0.01 and 0.001 degree). Especially relevant when coordinates have been rounded to protect sensitive species.

**Comment by peterdesmet** [comment]
Have to fix typo
