### ISSUE TITLE
How to map 'Road underpass/overpass/bridge'

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#26]
In GitLab by @peterdesmet on Aug 21, 2020, 3:00

CTMS has the [feature](https://inbo.github.io/ctms/terms/#Feature) `Road underpass/overpass/bridge`, which in camtrap is split in [feature_type](https://gitlab.com/oscf/camtrap-package-schemas/-/blob/master/deployments-table-schema.json#L209-210) `Road underpass`, `Road overpass`, `Road bridge`. 

- How can one now map the generic term? E.g. `Road tunnel/bridge`
- Is it necessary to have the specific terms?

**Comment by niconoe** [comment]
In GitLab by @kbubnicki on Aug 28, 2020, 15:50

That was copy/pasted from Wildlife Insights excel sheets:
https://docs.google.com/spreadsheets/d/1RCrg5guiNDYUkCijCSUgFvLwMQsCNf8DNUTaPddzAU0/edit#gid=0

I am open for any improvements. Also can be tagged with `community:feedback` label.

**Comment by kbubnicki** [comment]
Apparently no interest in the community to discuss this further at the moment, closing this issue.
