### ISSUE TITLE
Should image-based observations be restricted to AI observations?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#262]
With the plan to [split observations](https://github.com/tdwg/camtrap-dp/issues/203#issuecomment-1318656273) in event-based and image-based observations, I am curious what the exact use cases are for the image-based table.

I know AI typically assesses at the image level, e.g. this is the data we have in Agouti:

id | aimodel | asset | species | bbox | certainty | created_at
--- | -- | --- | --- | --- | --- | ---
1 | X | m1 | species Y | [73.75592803955078, 221.56085205078125, 225.87457275390625, 321.10198974609375] | 0.8415582180023193 | 
2 | X | m2 | species Y | [132.49847412109375, 218.109130859375, 255.0408935546875, 296.65924072265625] | 0.8237983584403992 | 

- Notice there is no count, sex, lifestage, etc.
- Notice too that it is technically possible to have the same image be assessed by multiple AI models (see #261). This would duplicate rows, but not throw of an aggregated sum over count (because there is no count).

## Question

**Is image-based classification also done by humans? Please let me know!**

Note: if not, then the `mediaobservations` table could be simplified a lot (and maybe even renamed) and support multiple assessments #261.

**Comment by peterdesmet** [comment]
I've now seen two instances (Agouti and @danstowell's ARISE implementation) where those AI observations are called `predictions`. If we reserve imageobservations for AI, we could call that table `predictions` and the event based ones (to be used for ecological analysis) `observations`.

**Comment by kbubnicki** [comment]
Hey,

My answer to this question is: **NO**, in my opinion, it is not a good idea to limit `mediaObservations` to AI predictions only for the following reasons:

1. The most straightforward use case is media-based training data for AI models which are obviously media-based human/expert observations. And this use case is critical in my opinion. 

2. Also think about already available datasets annotated at a media level. We would have to convert these datasets into `eventObservations` and that would be quite a "lossy" transformation of course.

3. Why should we at all limit "media Observations" to AI predictions only? I see no problem with having multiple rows for the same media until they can all be properly identified with `classificationMethod` & `classifiedBy`. This approach also gives you a possibility to have > 1 AI prediction in the `mediaObservations` table which can be important for #261

4. Another point for not splitting AI from human/expert observations is that I can imagine that, at some point, AI will also be able to produce `eventObservations` (tracking individual objects, assessing a real group size of all recorded animals during an (ecological) event etc)

Also I am against simplifying `mediaObservations` table (i.e. not including e.g. `sex`, `lifeStage`, `count` or `individualID`) - we would simply loose data and would put ourselves into the corner thinking about future developments of AI models - there are already AI models that can give you predictions of `sex` or `individuaID` of an animal!

**Comment by peterdesmet** [comment]
Not restricted to AI, discussed as part of Camtrap DP 0.6 #297.
