### ISSUE TITLE
Keep getting error message,  NA/NaN argument In addition: Warning messages: 1: NAs introduced by coercion  2: NAs introduced by coercion 

### ISSUE THREAD

**Issue by AmphibianScientist** [tdwg/camtrap-dp#263]
Hi all!

I am a new scientist and I am having issues with my coding. Here is the code I am trying to run:

```
{
  "name": "mammal-distributions-in-crandell-reserve-and-la-calandria-private-reserve-monteverde-costa-rica-20221201144500"
  "profile": "https://raw.githubusercontent.com/tdwg/camtrap-dp/<version>/camtrap-dp-profile.json"
  "resources": 
    {
      "name": "deployments"
      "schema": "https://raw.githubusercontent.com/tdwg/camtrap-dp/<version>/deployments-table-schema.json"
    }
    {
      "name": "media"
      "schema": "https://raw.githubusercontent.com/tdwg/camtrap-dp/<version>/media-table-schema.json"
    }
    {
      "name": "observations"
      "schema": "https://raw.githubusercontent.com/tdwg/camtrap-dp/<version>/observations-table-schema.json"
    }
}
```

I try to run it and I get this warning message:

Error in "name":"mammal-distributions-in-crandell-reserve-and-la-calandria-private-reserve-monteverde-costa-rica-20221201144500" : 
  NA/NaN argument
In addition: Warning messages:
1: NAs introduced by coercion 
2: NAs introduced by coercion 

What does that even mean? Can someone help me fix this issue? I've tried googling it and enter code commands to ignore this issue and so far it hasn't worked. I need to make a map or two for my presentation on Dec 8th. Please someone save me! Thanks in advance!

**Comment by peterdesmet** [comment]
Hi, where are you trying to run you this code?

1. Note that the code you pasted is not code that should be run, but rather how a `datapackage.json` file (a file that describes your csv files) should reference Camtrap DP (so it can be validated as camtrap data). See e.g. example: https://github.com/tdwg/camtrap-dp/blob/main/example/datapackage.json
2. Note also that Camtrap DP is not yet ready for production, so you may encounter issues.
3. If you to make a map right now, it might be easier to load your deployments into R, Python or a GIS program, and plot the coordinates on a map.

**Comment by AmphibianScientist** [comment]
I was trying to validate my datapackage.json. To be honest I am not quite sure what to do. I loaded and ran through the practice code and it was able to make the maps of the female mallards. I am really new to Rstudio, so I am not quite sure how to run all of my coding.

**Comment by peterdesmet** [comment]
@AmphibianScientist I will close your issue, as we cannot provide user support for Camtrap DP / R Studio. I hope you found a solution and that the use of Camtrap DP can be facilitated in the future once version 1.0 is out and the [camtraptor](https://inbo.github.io/camtraptor/) R package is updated to support that version.
