### ISSUE TITLE
Rephrase definition for cameraInterval

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#264]
[cameraInterval](https://tdwg.github.io/camtrap-dp/data/#deployments.camerainterval) is currently defined as:

> Time specified between shutter triggers when activity in the sensor will not trigger the shutter. Expressed in seconds.

Can this be rephrased to:

> Predefined duration after a trigger when activity detected by the camera sensor is ignored. Expressed in seconds.

Is that clearer? Does that convey the information correctly? @yliefting

**Comment by yliefting** [comment]
Yes, that's better. I find 'cameraInterval' still a bit vague but alternatives like 'quietPeriod', 'triggerCooldown' are similarly ambiguous. Let's keep 'cameraInterval' with the new explanation.

**Comment by peterdesmet** [comment]
I agree that the term `cameraInterval` doesn't immediately bring to mind what it is. Interval is maybe used as a synonym for "pause, delay", so maybe `cameraDelay` is better?

**Comment by kbubnicki** [comment]
I am fine with `cameraDelay` and a new definition.

**Comment by peterdesmet** [comment]
Note that the word `trigger` and `sensor` aren't mentioned anywhere else in Camtrap DP. I've already rephrased `detected by the camera sensor sensor` to `detected by the camera`, but what about trigger. Is it fine to reference as such:

> Predefined duration after a trigger when activity detected by the camera is ignored. Expressed in seconds.

Or should we use `after a capture`. Note that capture is referenced in `captureMethod`:

> Method used to capture the media file.

**Comment by peterdesmet** [comment]
Decided to keep it at:

> Predefined duration after a trigger when activity detected by the camera is ignored. Expressed in seconds.
