### ISSUE TITLE
Update links in example datapackage

### ISSUE THREAD

**Issue by damianooldoni** [tdwg/camtrap-dp#269]
I am using the [example datapackage](https://raw.githubusercontent.com/tdwg/camtrap-dp/main/example/datapackage.json) for testing camtraptor reading function. However, I get an error:

```
library(camtraptor)
dp_path <- "https://raw.githubusercontent.com/tdwg/camtrap-dp/main/example/datapackage.json"
dp <- read_camtrap_dp(
  file = dp_path,
  media = FALSE
)
#> Please make sure you have the right to access data from this Data Package for your intended use.
#> Follow applicable norms or requirements to credit the dataset and its authors.
#> Error: Can't find file at `https://raw.githubusercontent.com/tdwg/camtrap-dp/0.5/deployments-table-schema.json`.
```

The URL `https://raw.githubusercontent.com/tdwg/camtrap-dp/0.5/deployments-table-schema.json` is in https://github.com/tdwg/camtrap-dp/blob/bb046c85a55bef2ced709357c0047f0136df8326/example/datapackage.json#L10

Actually all links mention version 0.5 but such version is not in [tags](https://github.com/tdwg/camtrap-dp/tags).

**Comment by peterdesmet** [comment]
Good catch, forgot to create a tag. This is now done and the URLs to 0.5 resolve.

**Comment by damianooldoni** [comment]
Thanks for the fast reply, @peterdesmet!

**Comment by damianooldoni** [comment]
All tests in https://github.com/inbo/camtraptor/pull/186 passed. I will close this issue.
