### ISSUE TITLE
Add time range to observations

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#273]
Useful to indicate a temporal window within the video. See also #219.

**Comment by kbubnicki** [comment]
This will be solved with the new data model proposal #314 with adding columns `eventStart` and `eventEnd`. Can we close this one?

**Comment by peterdesmet** [comment]
See specifically commit 59cc20a496b40c4cdd6cd4c7f09547717dc0d082 to see how `eventStart`/`eventEnd` relate to Audivisual Core
