### ISSUE TITLE
Rename captureMethod `motion detection` to `activity detection`?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#280]
The controlled vocab for [captureMethod](https://tdwg.github.io/camtrap-dp/data/#media.capturemethod) is currently:

```
motion detection
time lapse
```

@jimcasaer @Tim-Hofmeester
1. Is "motion detection" sufficient here? Do some camera traps deploy other trigger mechanisms (e.g. heat increase).
2. Elsewhere we use `activity` rather than `motion`. Would you be ok if `motion detection` was renamed to `activity detection`

**Comment by peterdesmet** [comment]
Sorry, I submitted this issue before the description was complete. See updated issue description above at #280.

Ping @jimcasaer @Tim-Hofmeester

**Comment by jimcasaer** [comment]
@peterdesmet @Tim-Hofmeester 
1) I would suggest motion trigger
2) I would stick to motion rather than activity -- the activity levels of animals are something different from motion triggers etc

**Comment by peterdesmet** [comment]
Ok, so renaming the value `motion detection` to `motion trigger`?

**Comment by Tim-Hofmeester** [comment]
@peterdesmet 

I would like to raise a third option: "PIR-sensor trigger". That highlights that the camera is triggered by a PIR-sensor, which detects a change in a difference in thermal infrared (so most often a motion, but it doesn't necessarily have to be a motion). Although not very commonly used anymore, there used to be camera traps with other trigger devices, such as e.g., an AIR (active infrared) sensor or a mechanical sensor (such as cameras that are triggered by animals standing on a plate with a mechanical trigger underneath the plate). Not sure if those would need to be included as they are rather uncommon.

**Comment by kbubnicki** [comment]
I agree with @jimcasaer that the activity is sth else, especially amongst camera trappers / animal ecologists. I do not see a critical difference between `detection` and `trigger` as the second part.

As for PIR sensors - good suggestion by @Tim-Hofmeester but I think that the information about what kind of sensors were used can be extracted (though indirectly) from `cameraModel` field.

**Comment by peterdesmet** [comment]
Ok, I would leave the term as is then, a quite broadly applicable `motion detection`.
