### ISSUE TITLE
Fix broad/narrow descriptions on website

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#284]
A broad match is:

> SKOS mapping relation (for use with P4390): the concept represented by the external entity is broader than the item

For example: `dwc:eventID` (the external entity) is broader than the more specific `deploymentID` (the item), hence `broadMatch`:

https://github.com/tdwg/camtrap-dp/blob/a9c78b3f12c78590157eadc878c53eac80e35f37/deployments-table-schema.json#L6-L17

On the [website](https://tdwg.github.io/camtrap-dp/data/#deployments.deploymentid) however, the relationship is described in the other direction, i.e. `[deployment ID] is broader than [eventID]`. **That is incorrect and should be reversed.**

<img width="748" alt="Screenshot 2023-02-08 at 19 07 25" src="https://user-images.githubusercontent.com/600993/217615303-0136ffb8-4bec-4c9d-a601-2c46f65ff4ed.png">

@baskaufs am I interpreting this correctly?

**Comment by baskaufs** [comment]
Yes, I believe so. The broadMatch relationship has the narrower resource as the subject and the broader resource as the value (i.e. object in RDF terms).
