### ISSUE TITLE
Are Camtrap DP terms narrower or same as referenced terms from other standards?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#288]
@baskaufs @tucotuco

## Issue

Camtrap DP terms link to terms described in other standards (DwC, DC, AC, ...) to help users crosswalk. The relation can be described as:

- Term in standard is a `broadMatch` of Camtrap DP term
- Term in standard is an `exactMatch` of Camtrap DP term
- Term in standard is a `narrowMatch` of Camtrap DP term

Since Camtrap DP has a limited scope (it's about camera trap datasets), should we always indicate the links as `broadMatch` to Camtrap DP term? Or is it fair to use `exactMatch` sometimes?

### bibliographicCitation
- DC: A bibliographic reference for the resource.
- Camtrap DP: Bibliographic/recommended citation for the package.

### scientificName
- DwC: The full scientific name, with authorship and date information if known. When forming part of an Identification, this should be the name in lowest level taxonomic rank that can be determined. This term should not contain identification qualifications, which should instead be supplied in the IdentificationQualifier term.
- Camtrap DP: Scientific name of the observed individual(s).

### eventID / deploymentID
- DwC: An identifier for the set of information associated with an Event (something that occurs at a place and time). May be a global unique identifier or an identifier specific to the data set.
- Camtrap DP: Unique identifier of the deployment.

### decimalLatitude / latitude
- DwC: The geographic latitude (in decimal degrees, using the spatial reference system given in geodeticDatum) of the geographic center of a Location. Positive values are north of the Equator, negative values are south of it. Legal values lie between -90 and 90, inclusive.
- Camtrap DP: Latitude of the deployment location in decimal degrees, using the WGS84 datum.

### Package

- [x] http://purl.org/dc/terms/bibliographicCitation `skos:exactMatch` of [bibliographicCitation](https://tdwg.github.io/camtrap-dp/metadata/#bibliographicCitation)
- [x] http://rs.tdwg.org/hc/terms/inventoryTypes `skos:broadMatch` of [samplingDesign](https://tdwg.github.io/camtrap-dp/metadata/#samplingDesign)
- [x] http://rs.tdwg.org/dwc/terms/coordinatePrecision `skos:exactMatch` of [coordinatePrecision](https://tdwg.github.io/camtrap-dp/metadata/#coordinatePrecision)
- [x] http://purl.org/dc/terms/spatial `skos:exactMatch` of [spatial](https://tdwg.github.io/camtrap-dp/metadata/#spatial)
- [x] http://purl.org/dc/terms/temporal `skos:exactMatch` of [temporal](https://tdwg.github.io/camtrap-dp/metadata/#temporal)
- [x] http://rs.tdwg.org/dwc/terms/taxonID `skos:exactMatch` of [taxonID](https://tdwg.github.io/camtrap-dp/metadata/#taxonID)
- [x] http://rs.tdwg.org/dwc/terms/scientificName `skos:exactMatch` of [scientificName](https://tdwg.github.io/camtrap-dp/metadata/#scientificName)
- [x] http://rs.tdwg.org/dwc/terms/taxonRank `skos:exactMatch` of [taxonRank](https://tdwg.github.io/camtrap-dp/metadata/#taxonRank)
- [x] http://rs.tdwg.org/dwc/terms/kingdom `skos:exactMatch` of [kingdom](https://tdwg.github.io/camtrap-dp/metadata/#kingdom)
- [x] http://rs.tdwg.org/dwc/terms/phylum `skos:exactMatch` of [phylum](https://tdwg.github.io/camtrap-dp/metadata/#phylum)
- [x] http://rs.tdwg.org/dwc/terms/class `skos:exactMatch` of [class](https://tdwg.github.io/camtrap-dp/metadata/#class)
- [x] http://rs.tdwg.org/dwc/terms/order `skos:exactMatch` of [order](https://tdwg.github.io/camtrap-dp/metadata/#order)
- [x] http://rs.tdwg.org/dwc/terms/family `skos:exactMatch` of [family](https://tdwg.github.io/camtrap-dp/metadata/#family)
- [x] http://rs.tdwg.org/dwc/terms/genus `skos:exactMatch` of [genus](https://tdwg.github.io/camtrap-dp/metadata/#genus)
- [x] http://rs.tdwg.org/dwc/terms/vernacularName `skos:exactMatch` of [vernacularName](https://tdwg.github.io/camtrap-dp/metadata/#vernacularName)
- [x] https://schema.datacite.org/meta/kernel-4.4/include/datacite-relationType-v4.xsd `skos:exactMatch` of [relationType](https://tdwg.github.io/camtrap-dp/metadata/#relationType)
- [x] https://schema.datacite.org/meta/kernel-4.4/include/datacite-resourceType-v4.xsd `skos:exactMatch` of [resourceTypeGeneral](https://tdwg.github.io/camtrap-dp/metadata/#resourceTypeGeneral)
- [x] https://schema.datacite.org/meta/kernel-4.4/include/datacite-relatedIdentifierType-v4.xsd `skos:exactMatch` of [relatedIdentifierType](https://tdwg.github.io/camtrap-dp/metadata/#relatedIdentifierType)

### Deployments

- [x] http://rs.tdwg.org/dwc/terms/eventID `skos:broadMatch` of [deploymentID](https://tdwg.github.io/camtrap-dp/data/#deployments.deploymentID)
- [x] http://rs.tdwg.org/dwc/terms/locationID `skos:exactMatch` of [locationID](https://tdwg.github.io/camtrap-dp/data/#deployments.locationID)
- [x] http://rs.tdwg.org/dwc/terms/locality `skos:exactMatch` of [locationName](https://tdwg.github.io/camtrap-dp/data/#deployments.locationName)
- [x] http://rs.tdwg.org/dwc/terms/decimalLatitude `skos:exactMatch` of [latitude](https://tdwg.github.io/camtrap-dp/data/#deployments.latitude) **Changed to skos:broadMatch in 5da2692**
- [x] http://rs.tdwg.org/dwc/terms/decimalLongitude `skos:exactMatch` of [longitude](https://tdwg.github.io/camtrap-dp/data/#deployments.longitude) **Changed to skos:broadMatch in 5da2692**
- [x] http://rs.tdwg.org/dwc/terms/coordinateUncertaintyInMeters `skos:exactMatch` of [coordinateUncertainty](https://tdwg.github.io/camtrap-dp/data/#deployments.coordinateUncertainty)
- [x] http://rs.tdwg.org/dwc/terms/eventDate `skos:exactMatch` of [start](https://tdwg.github.io/camtrap-dp/data/#deployments.start) **Changed to skos:broadMatch in 5da2692**
- [x] http://rs.tdwg.org/dwc/terms/eventDate `skos:exactMatch` of [end](https://tdwg.github.io/camtrap-dp/data/#deployments.end) **Changed to skos:broadMatch in 5da2692**
- [x] http://rs.tdwg.org/hc/terms/samplingPerformedBy `skos:broadMatch` of [setupBy](https://tdwg.github.io/camtrap-dp/data/#deployments.setupBy)
- [x] http://rs.tdwg.org/ac/terms/captureDevice `skos:broadMatch` of [cameraModel](https://tdwg.github.io/camtrap-dp/data/#deployments.cameraModel)
- [x] http://rs.tdwg.org/dwc/terms/habitat `skos:exactMatch` of [habitat](https://tdwg.github.io/camtrap-dp/data/#deployments.habitat)
- [x] http://rs.tdwg.org/ac/terms/tag `skos:narrowMatch` of [tags](https://tdwg.github.io/camtrap-dp/data/#deployments.tags) **Changed to skos:exactMatch in 8c25523**
- [x] http://rs.tdwg.org/dwc/terms/eventRemarks `skos:exactMatch` of [comments](https://tdwg.github.io/camtrap-dp/data/#deployments.comments)

### Media

- [x] http://purl.org/dc/terms/identifier `skos:broadMatch` of [mediaID](https://tdwg.github.io/camtrap-dp/data/#media.mediaID)
- [x] http://rs.tdwg.org/dwc/terms/parentEventID `skos:broadMatch` of [deploymentID](https://tdwg.github.io/camtrap-dp/data/#media.deploymentID)
- [x] http://rs.tdwg.org/dwc/terms/eventID `skos:broadMatch` of [eventID](https://tdwg.github.io/camtrap-dp/data/#media.eventID)
- [x] http://rs.tdwg.org/ac/terms/resourceCreationTechnique `skos:broadMatch` of [captureMethod](https://tdwg.github.io/camtrap-dp/data/#media.captureMethod)
- [x] http://ns.adobe.com/xap/1.0/CreateDate `skos:exactMatch` of [timestamp](https://tdwg.github.io/camtrap-dp/data/#media.timestamp)
- [x] http://rs.tdwg.org/ac/terms/accessURI `skos:broadMatch` of [filePath](https://tdwg.github.io/camtrap-dp/data/#media.filePath)
- [x] http://rs.tdwg.org/ac/terms/comments `skos:exactMatch` of [comments](https://tdwg.github.io/camtrap-dp/data/#media.comments)

### Observations

- [x] http://rs.tdwg.org/dwc/terms/occurrenceID `skos:exactMatch` of [observationID](https://tdwg.github.io/camtrap-dp/data/#observations.observationID) **Changed to skos:broadMatch in 5da2692**
- [x] http://rs.tdwg.org/dwc/terms/eventID `skos:broadMatch` of [eventID](https://tdwg.github.io/camtrap-dp/data/#observations.eventID)
- [x] http://rs.tdwg.org/dwc/terms/taxonID `skos:exactMatch` of [taxonID](https://tdwg.github.io/camtrap-dp/data/#observations.taxonID)
- [x] http://rs.tdwg.org/dwc/terms/scientificName `skos:exactMatch` of [scientificName](https://tdwg.github.io/camtrap-dp/data/#observations.scientificName)
- [x] http://rs.tdwg.org/dwc/terms/individualCount `skos:exactMatch` of [count](https://tdwg.github.io/camtrap-dp/data/#observations.count)
- [x] http://rs.tdwg.org/dwc/terms/lifeStage `skos:exactMatch` of [lifeStage](https://tdwg.github.io/camtrap-dp/data/#observations.lifeStage)
- [x] http://rs.tdwg.org/dwc/terms/sex `skos:exactMatch` of [sex](https://tdwg.github.io/camtrap-dp/data/#observations.sex)
- [x] http://rs.tdwg.org/dwc/terms/behavior `skos:exactMatch` of [behavior](https://tdwg.github.io/camtrap-dp/data/#observations.behavior)
- [x] http://rs.tdwg.org/dwc/terms/organismID `skos:exactMatch` of [individualID](https://tdwg.github.io/camtrap-dp/data/#observations.individualID)
- [x] http://rs.tdwg.org/dwc/terms/identifiedBy `skos:exactMatch` of [classifiedBy](https://tdwg.github.io/camtrap-dp/data/#observations.classifiedBy)
- [x] http://rs.tdwg.org/dwc/terms/dateIdentified `skos:exactMatch` of [classificationTimestamp](https://tdwg.github.io/camtrap-dp/data/#observations.classificationTimestamp) **Changed to skos:broadMatch in 5da2692**
- [x] http://rs.tdwg.org/ac/terms/tag `skos:exactMatch` of [tags](https://tdwg.github.io/camtrap-dp/data/#observations.comments)
- [x] http://rs.tdwg.org/dwc/terms/occurrenceRemarks `skos:exactMatch` of [comments](https://tdwg.github.io/camtrap-dp/data/#observations.comments)

**Comment by tucotuco** [comment]
I would say that exactMatch mappings should be used wherever warranted. I
would replace a few of your mappings with the following:
http://rs.tdwg.org/dwc/terms/decimalLatitude skos:broadMatch of latitude
<https://tdwg.github.io/camtrap-dp/data/#latitude>
http://rs.tdwg.org/dwc/terms/decimalLongitude skos:broadMatch of longitude
<https://tdwg.github.io/camtrap-dp/data/#longitude>
http://rs.tdwg.org/dwc/terms/eventDate skos:broadMatch of start
<https://tdwg.github.io/camtrap-dp/data/#start>
http://rs.tdwg.org/dwc/terms/eventDate skos:broadMatch of end
<https://tdwg.github.io/camtrap-dp/data/#end>
http://rs.tdwg.org/dwc/terms/occurrenceID skos:broadMatch of observationID
<https://tdwg.github.io/camtrap-dp/data/#observationID>
http://rs.tdwg.org/dwc/terms/dateIdentified skos:broadMatch of
classificationTimestamp
<https://tdwg.github.io/camtrap-dp/data/#classificationTimestamp>

**Comment by peterdesmet** [comment]
Thanks John, I've updated those 6 relations in 5da2692.

**Comment by peterdesmet** [comment]
Addressed in Camtrap DP 0.6 #297.
