### ISSUE TITLE
Rethink the use of the word `Type` in term names

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#300]
A number of fields have a controlled vocabulary:

level | term | values
--- | --- | ---
package.contributors | `role` | contact, principalInvestigator, ...
package.licenses | `scope` | data, media
package.project | `samplingDesign` | simpleRandom, systematicRandom, ...
package.project | `captureMethod` | motionDetection, timeLapse
package.taxonomic | `taxonRank` | kingdom, phylum, ...
package.relatedIdentifiers | `relationType` | IsCitedBy, Cites, IsSupplementTo, ...
package.relatedIdentifiers | `resourceTypeGeneral` | Audiovisual, Book, BookChapter, ...
package.relatedIdentifiers | `relatedIdentifierType` | ARK, arXiv, bibcode, ...
deployments | `featureType` | roadPaved, roadDirt, trailHiking, ...
media | `captureMethod` | motionDetection, timeLapse
obs | `observationType` | animal, human, vehicle, ...
obs | `cameraSetupType` | setup, calibration, ...
obs | `lifeStage` | adult, subadult, juvenile
obs | `sex` | male, female
obs | `classificationMethod` | human, machine

Some have `Type` in their name, while others don't (e.g. featureType vs classificationMethod). I think we should drop the word `Type` where it isn't necessary:

- [ ] `featureType` -> `feature`: the term originally came from CTMS, but it would be more consistent to use `feature` here (cf. `habitat`)
- [ ] `observationType` -> `observationCategory` or keep as is
- [ ] `cameraSetupType` -> `cameraSetup` (i.e. reverting a recent change)
- [ ] `fileMediatype` -> `fileMediaType`: "media type" is an [existing term](https://en.wikipedia.org/wiki/Media_type) so would keep it. But it is written in two words and should therefore be written as `mediaType`
- [ ] `relationType`, `resourceTypeGeneral`, `relatedIdentifierType`: keep as is. These terms are borrowed directly from DataCite.

Thoughts? @kbubnicki @tucotuco and others ...

**Comment by tucotuco** [comment]
I feel pretty strongly that anywhere that things can be made more clear, they should be. Labels are one of those places where it can make a big difference because people are less likely to go any further to divine what a term actually means. With that in mind, if I saw a term feature, I would expect to put features in it. I'll use a gazetteer example to illustrate the point. In a gazetteer, a feature might be "Cerro Tronador", an instance of a feature, whereas its featureType might be "mountain".  Based on that alone I would keep "Type" in the term name wherever it is applicable.

**Comment by peterdesmet** [comment]
I see your point. The approach could then be:

- [x] `role`: leave as is, from Frictionless. Already implies a controlled vocab.
- [x] `scope`: leave as is. Hasn't anything to do with type.
- [ ] `samplingDesign`: rename to `samlingDesignType` to indicate we're not expecting a description? Or use `samplingMethod`?
- [ ] `captureMethod`: leave as is? Are terms ending with `Method` clear enough as a type field? Would `captureMethodType` be better?
- [x] `taxonRank`: leave as. Already implies a vocab.
- [x] `relationType`: leave as is, from DataCite
- [x] `resourceTypeGeneral`: leave as is, from DataCite
- [x] `relatedIdentifierType`: leave as is, from DataCite
- [x] `featureType`: leave as is
- [x] `observationType`: leave as is
- [x] `cameraSetupType`: leave as is
- [x] `lifeStage`: leave as is. Already implies a vocab.
- [x] `sex`: leave as is. Already implies a vocab.
- [ ] `classificationMethod`: leave as is? Are terms ending with `Method` clear enough as a type field? Would `classificationMethodType` be better?

Feedback on the questions welcome.

**Comment by tucotuco** [comment]
The method ones are tricky. They suggest (to me anyway) that a description would be OK. Yet appending "Type" to them suggests (to me) a higher level category of methods. 

samplingMethod sort of has a precedent in [samplingProtocol](https://dwc.tdwg.org/terms/#dwc:samplingProtocol). Not sure if that is a good enough match to make that change, and it doesn't help with the impression that a description would be OK.

**Comment by peterdesmet** [comment]
Discussed with @kbubnicki 

- Standardizing all names to `method` (`samplingDesign` -> `samplingMethod`, `captureMethod`, `classificationMethod`) is not ideal for `samplingDesign`. It is indicated as "sampling design" in the reference [Wearn & Glover-Kapfer (2017)](https://doi.org/10.13140/RG.2.2.23409.17767) and is different than `samplingMethod` (which one would assume is `camera trap`)
- Renaming to `samplingDesignType`, `captureMethodType`, `classificationMethodType` (or `samplingType`, `captureType`, `classificationType`) might help newcomers understand that these fields are to be used with a controlled vocabulary (rather than a full description or URL), but they are also quite verbose. Other fields (see above) with controlled vocabs are not necessarily named `type` either and the documentation always provides the vocabulary and tests will warn if incorrect values are used.

So closing this issue without taking further action.
