### ISSUE TITLE
Use `definitions` not `$defs`

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#313]
Issue reported at https://github.com/gbif/ipt/issues/1955#issuecomment-1501819698

**Comment by peterdesmet** [comment]
We adopted `$defs` based on [this recommendation](https://json-schema.org/understanding-json-schema/structuring.html#defs):

> Although we can identify any subschema using JSON Pointers or named anchors, the `$defs` keyword gives us a standardized place to keep subschemas intended for reuse in the current schema document.

The issue with it not being recognized seems to be related to the datapackage-java implementation, as commented by @mike-podolskiy90 in https://github.com/gbif/ipt/issues/1955#issuecomment-1504784813:

> Data package fails to generate and error is displayed:
> ```
> Reference #$defs/version cannot be resolved
> ```
> It happens under the hood in the frictionless datapackage-java. It can be a problem with the datapackage-java itself though. Anyway, I changed it as described above, and it works just fine: https://rs.gbif.org/sandbox/experimental/camtrap-dp/0.6/profile/camtrap-dp-profile.json

---

We would therefore prefer to keep the `$defs` convention and have it fixed in datapackage-java. @mike-podolskiy90 have you been in contact with the developers? If it cannot be fixed in datapackage-java, we could either change it in Camtrap DP or (manually) for the IPT schemas.

**Comment by mike-podolskiy90** [comment]
It's fixed in the profile schema (rs.gbif.org). I think that is enough
