### ISSUE TITLE
Optional Longitude and Latitude on Deployments

### ISSUE THREAD

**Issue by bencevans** [tdwg/camtrap-dp#335]
Fantastic work on the specification!

I don't know how widespread this concern may be, but I know some of our collaborators are open to sharing camera trap datasets publicly, however, the geospatial coordinates are unlikely to be released due to sensitivity at particular sites. In a few circumstances, they weren't collected, and it would be great to still represent them in a standardised form.

As the deployment is still uniquely identified by its ID, and the locationID property is optional, can the latitude and longitude properties be made optional too? Maybe requiring either `locationID OR (latitude AND longitude)` if it's imperative some form of location is identified.

**Comment by peterdesmet** [comment]
Thanks for the question Ben!

1. Unfortunately, the Frictionless specification we use currently doesn't support conditional requirements ([it would be great if it did](https://github.com/tdwg/camtrap-dp/issues/32)), so defining a `locationID OR (latitude AND longitude)` is not possible.
2. Geospatial coordinates are so critical to many analyses, that I would prefer to keep them required, so validation can warn users if they are missing.
3. While geospatial coordinates are required, it is possible to fuzzy these for particular sites. Any fuzzy method can be used (coordinate rounding, random assignment within an extent, etc.) as long as the resulting [coordinateUncertainty](https://tdwg.github.io/camtrap-dp/data/#deployments.coordinateUncertainty) (in meters) is indicated. For example, coordinates for non-sensitive sites could be provided with precise coordinates and a low uncertainty (e.g. 10m), while sensitive sites could be provided with rounded coordinates and a high uncertainty (e.g. 5000m). One should also make sure that coordinates of sensitive sites cannot easily be obtained by looking at the dataset as a whole (e.g. if all locations are gridded).
4. In addition, one can flat out lower the coordinate precision for all coordinates. Users are warned of this via the [coordinatePrecision](https://tdwg.github.io/camtrap-dp/metadata/#coordinatePrecision) property in the metadata. The lowest precision allowed is degree level, which has an [uncertainty of 112km or higher](https://docs.gbif.org/georeferencing-best-practices/1.0/en/#table-uncertainty).

I hope these options meets the concerns of your collaborators?

**Comment by bencevans** [comment]
Perfect, thank you, @peterdesmet. I'll set the coordinate to the country's centre point with uncertainty covering the land. I've generated a list of centroids and radius from the natural earth data if useful to anyone else https://github.com/bencevans/world-country-centroids-radius. Cheers!
