### ISSUE TITLE
Link `filePublic` to `ac:serviceExpectation`

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#339]
The term https://tdwg.github.io/camtrap-dp/data/#media.filePublic can potentially have a skos link to https://ac.tdwg.org/termlist/#ac_serviceExpectation, although one is a boolean and the other a controlled vocab. Need to assess if it is same, narrow or broader.

**Comment by peterdesmet** [comment]
@danstowell @baskaufs @edwbaker

Preface: Camtrap DP's media [filePath](https://camtrap-dp.tdwg.org/data/#media.filePath) is skos-linked to Audiovisual Core's [accessURI](https://ac.tdwg.org/termlist/#ac_accessURI), since the terms are clearly related. The Camtrap DP term is narrower, since it does not allow offline resources such as the DOI of a CD. It does allow full URLs and relative paths, which both seem to be accepted by `accessURI` as well.

Question: Camtrap DP also has a term [filePublic](https://camtrap-dp.tdwg.org/data/#media.filePublic). **Do you think it is OK to skos-link this to Audiovisual Core's [serviceExpectation](https://ac.tdwg.org/termlist/#ac_serviceExpectation)?**

- [Camtrap DP: filePublic](https://camtrap-dp.tdwg.org/data/#media.filePublic): `false` if the media file is not publicly accessible (e.g. to protect the privacy of people).
- [AC: serviceExpectation](https://ac.tdwg.org/termlist/#ac_serviceExpectation): A term that describes what service expectations users may have of the ac:accessURI. Recommended terms include `online` (denotes that the URL is expected to deliver the resource), `authenticate` (denotes that the URL delivers a login or other authentication interface requiring completion before delivery of the resource) `published` (non digital) (denotes that the URL is the identifier of a non-digital published work, for example a doi.) Communities should develop their own controlled vocabularies for Service Expectations.

The `filePublic` term is a more **narrow** interpretation (digital resources only) and it uses "their own controlled vocabularies" as a **boolean**. `true` can be mapped to `"online"`. `false` can arguably be mapped to `"authenticate"`, although the authentication to get access to non-public media file can vary and might not be provided through the provided URL.

**Comment by baskaufs** [comment]
@peterdesmet I think your argument is pretty convincing that boolean values represent a community-developed controlled vocabulary. So I can't think of any reason not to map them as at least a close match.
