### ISSUE TITLE
Support CRediT roles for contributors

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#343]
**Based on comment from reviewer.**

Should `contributors` adopt roles that align with the [CRediT (Contributor Roles Taxonomy)](https://credit.niso.org/)?

- [Conceptualization](http://159.203.176.220/contributor-roles/conceptualization/)
- [Data curation](http://159.203.176.220/contributor-roles/data-curation/)
- [Formal Analysis](http://159.203.176.220/contributor-roles/formal-analysis/)
- [Funding acquisition](http://159.203.176.220/contributor-roles/funding-acquisition/)
- [Investigation](http://159.203.176.220/contributor-roles/investigation/)
- [Methodology](http://159.203.176.220/contributor-roles/methodology/)
- [Project administration](http://159.203.176.220/contributor-roles/project-administration/)
- [Resources](http://159.203.176.220/contributor-roles/resources/)
- [Software](http://159.203.176.220/contributor-roles/software/)
- [Supervision](http://159.203.176.220/contributor-roles/supervision/)
- [Validation](http://159.203.176.220/contributor-roles/validation/)
- [Visualization](http://159.203.176.220/contributor-roles/visualization/)
- [Writing – original draft](http://159.203.176.220/contributor-roles/writing-original-draft/)
- [Writing – review & editing](http://159.203.176.220/contributor-roles/writing-review-editing/)

**Comment by Tim-Hofmeester** [comment]
The reviewer mentioned the MeRIT system [https://www.nature.com/articles/s41467-023-37039-1](url) which builds upon the CRediT system but suggests to be more specific when it comes to the methodology. My translation to camera trap data would be that one could specify the contributor roles more specifically tailored to camera trap studies, e.g., "set-up of cameras", "retrieval of cameras", "classification of images" etc. This would allow for total transparency about what each contributor contributed with. I think such a system would be good, but needs some thinking/development to create useful and complete roles/contributions.

**Comment by peterdesmet** [comment]
Note that it is possible to indicate _in the data_ who set up each camera in [setupBy](https://camtrap-dp.tdwg.org/data/#deployments.setupBy) and who classified each observation in [classifiedBy](https://camtrap-dp.tdwg.org/data/#observations.classifiedBy). This is at a much more detailed level than is possible in the metadata/methodology and in my opinion what MeRIT strives to do ("more granularity"). Still, we could _also_ indicate more detailed roles the the five we currently have.

**Comment by Tim-Hofmeester** [comment]
> Note that it is possible to indicate _in the data_ who set up each camera in [setupBy](https://camtrap-dp.tdwg.org/data/#deployments.setupBy) and who classified each observation in [classifiedBy](https://camtrap-dp.tdwg.org/data/#observations.classifiedBy). This is at a much more detailed level than is possible in the metadata/methodology and in my opinion what MeRIT strives to do ("more granularity"). Still, we could _also_ indicate more detailed roles the the five we currently have.

Great, I had missed that this is already covered by setupBy and classifiedBy! I fully agree that this is better as it is at a more detailed level.
