### ISSUE TITLE
Use more neutral term for captureMethod `motionDetection `

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#360]
We currently allow 2 values for [captureMethod](https://camtrap-dp.tdwg.org/data/#media.captureMethod):

```
timelapse
motionDetection
```

@dhobern indicated that `timelapse` is pretty straightforward, but `motionDetection` might be a bit too narrow a term to express that the camera automatically detected something, resulting in a trigger that captured the media. PIR sensors use a combination of motion _and heat_ to trigger the camera and if we want to eventually allow audio sensors, then it might just be sound (not motion) that is used to capture a media file.

We could rename to:

- `trigger`: cf. https://docs.gbif-uat.org/camera-trap-guide/en/#trigger, but the term is also used to indicate the series of images captured as result of a trigger
- `detection`: quite a broad term, but fits nicely with e.g. [detectionDistance](https://camtrap-dp.tdwg.org/data/#deployments.detectionDistance)
- `activityDetection`: a bit narrower, while still leaving it open _how_ it was measured.

I prefer `detection`.

I would also rephrase [cameraDelay](https://camtrap-dp.tdwg.org/data/#deployments.cameraDelay):

> Predefined duration after a ~trigger~ **detection** when activity detected by the camera is ignored. Expressed in seconds.

To remove the term `trigger` altogether

**Comment by ben-norton** [comment]
It would be ideal to somehow use the infared heat detection aspect of the capture event. That is important in the broader community that animals like reptiles aren't readily detected using PIR sensors. If you went with detection then you lose that infared context. It becomes somewhat arbitrary how the animal was detected. A new technology/technique might make its way down the pipeline to camera traps that's distinctly different than infared. Maybe infaredDetection, thermalDetection?

**Comment by peterdesmet** [comment]
Discussed with @kbubnicki. We want to keep the **very broad categorization** for this term. More specific (infrared, thermal, etc.) might be harder to provide by users and there is currently no use case for it. Suggested changes:

- Rename value to **`activityDetection`** to express the broad concept of "sensor detected activity through undefined method". This would then also include the audio detection of a non-moving stridulating grasshopper, which is would be excluded by the current term `motionDetection`.
- Remove "trigger" from cameraDelay and rephrase as:
  > Predefined duration after detection when further activity is ignored. Expressed in seconds.
