### ISSUE TITLE
Support combining Camtrap DP into one, i.e. support multiple projects

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/camtrap-dp#380]
A use case that comes up quite often is that researchers want to combine Camtrap DP into one Camtrap DP to do a meta analysis. Software could support this and the result would be:

1. Deployments: combination of deployments (but check that `deploymentID` remains unique)
2. Deployments could benefit from having an optional `projectID`
3. Media: combination of media (but check that `mediaID` remains unique)
4. Observations: combination of media (but check that `observationID` remains unique)
5. [name](https://camtrap-dp.tdwg.org/metadata/#name): a new name is created (old values are not retained)
6. [id](https://camtrap-dp.tdwg.org/metadata/#id): a new ID is created. The original ids are stored in [relatedIdentifiers](https://camtrap-dp.tdwg.org/metadata/#relatedIdentifiers)
7. [created](https://camtrap-dp.tdwg.org/metadata/#created): reset to current timestamp (old values are not retained)
8. [title](https://camtrap-dp.tdwg.org/metadata/#title): a new title (old values are not retained)
9. [contributors](https://camtrap-dp.tdwg.org/metadata/#contributors): a combination is made, duplicates (on some or all fields) are removed and roles are combined (in Frictionless v2). The order is not retained.
10. [description](https://camtrap-dp.tdwg.org/metadata/#description): a new one is generated, potentially still listing the previous descriptions
11. [version](https://camtrap-dp.tdwg.org/metadata/#version): is reset to 1.0 (old values are not retained)
12. [keywords](https://camtrap-dp.tdwg.org/metadata/#keywords): a combination is made, duplicates are removed
13. [image](https://camtrap-dp.tdwg.org/metadata/#image): is removed (old values are not retained)
14. [homepage](https://camtrap-dp.tdwg.org/metadata/#homepage): is removed (old values are not retained)
15. [sources](https://camtrap-dp.tdwg.org/metadata/#sources): a combination is made, duplicates are removed
16. [licenses](https://camtrap-dp.tdwg.org/metadata/#licenses): a combination is made, duplicates are removed. If e.g. two different license with `scope: media` are listed, it won't be clear which one applies to which media.
17. [bibliographicCitation](https://camtrap-dp.tdwg.org/metadata/#bibliographicCitation): is removed (old values are not retained)
18. [project](https://camtrap-dp.tdwg.org/metadata/#project): ideally this becomes an array of projects and deployments have a `projectID` to link to the correct project info.
19. [coordinatePrecision](https://camtrap-dp.tdwg.org/metadata/#coordinatePrecision): is reset to least precise precision (old values are not retained)
20. [spatial](https://camtrap-dp.tdwg.org/metadata/#spatial): is reset based on new deployments (old values are not retained)
21. [temporal](https://camtrap-dp.tdwg.org/metadata/#temporal): is reset based on new deployments (old vales are not retained)
22. [taxonomic](https://camtrap-dp.tdwg.org/metadata/#taxonomic): a combination is made, duplicates are removed.
23. [relatedIdentifiers](https://camtrap-dp.tdwg.org/metadata/#relatedIdentifiers): a combination is made, duplicates are removed
24. [references](https://camtrap-dp.tdwg.org/metadata/#references): a combination is made, duplicates are removed

The main issue is `project` (and to lesser extend `licenses`). I think supporting multiple `projects` and adding a `projectID` to deployments would be the way forward. Software that only supports one project can either populate just one or read only the first one. For consistency, I would rename to plural `projects` (cf. `licenses`, `sources`, `references`).

**Comment by sannegovaert** [comment]
Task list:

- [ ] Deployments: combination of deployments (but check that deploymentID remains unique)
- [ ] Media: combination of media (but check that mediaID remains unique)
- [ ] Observations: combination of media (but check that observationID remains unique)
- [ ] [name](https://camtrap-dp.tdwg.org/metadata/#name): a new name is created (old values are not retained)
- [ ] [id](https://camtrap-dp.tdwg.org/metadata/#id): a new ID is created. The original ids are stored in [relatedIdentifiers](https://camtrap-dp.tdwg.org/metadata/#relatedIdentifiers)
- [ ] [created](https://camtrap-dp.tdwg.org/metadata/#created): reset to current timestamp (old values are not retained)
- [ ] [title](https://camtrap-dp.tdwg.org/metadata/#title): a new title (old values are not retained)
- [ ] [contributors](https://camtrap-dp.tdwg.org/metadata/#contributors): a combination is made, duplicates (on some or all fields) are removed and roles are combined (in Frictionless v2). The order is not retained.
- [ ] [description](https://camtrap-dp.tdwg.org/metadata/#description): a new one is generated, potentially still listing the previous descriptions
- [ ] [version](https://camtrap-dp.tdwg.org/metadata/#version): is reset to 1.0 (old values are not retained)
- [ ] [keywords](https://camtrap-dp.tdwg.org/metadata/#keywords): a combination is made, duplicates are removed
- [ ] [image](https://camtrap-dp.tdwg.org/metadata/#image): is removed (old values are not retained)
- [ ] [homepage](https://camtrap-dp.tdwg.org/metadata/#homepage): is removed (old values are not retained)
- [ ] [sources](https://camtrap-dp.tdwg.org/metadata/#sources): a combination is made, duplicates are removed
- [ ] [licenses](https://camtrap-dp.tdwg.org/metadata/#licenses): a combination is made, duplicates are removed. If e.g. two different license with scope: media are listed, it won't be clear which one applies to which media.
- [ ] [bibliographicCitation](https://camtrap-dp.tdwg.org/metadata/#bibliographicCitation): is removed (old values are not retained)
- [ ] [project](https://camtrap-dp.tdwg.org/metadata/#project): ideally this becomes an array of projects and deployments have a projectID to link to the correct project info.
- [ ] [coordinatePrecision](https://camtrap-dp.tdwg.org/metadata/#coordinatePrecision): is reset to least precise precision (old values are not retained)
- [ ] [spatial](https://camtrap-dp.tdwg.org/metadata/#spatial): is reset based on new deployments (old values are not retained)
- [ ] [temporal](https://camtrap-dp.tdwg.org/metadata/#temporal): is reset based on new deployments (old vales are not retained)
- [ ] [taxonomic](https://camtrap-dp.tdwg.org/metadata/#taxonomic): a combination is made, duplicates are removed.
- [ ] [relatedIdentifiers](https://camtrap-dp.tdwg.org/metadata/#relatedIdentifiers): a combination is made, duplicates are removed
- [ ] [references](https://camtrap-dp.tdwg.org/metadata/#references): a combination is made, duplicates are removed

**Comment by peterdesmet** [comment]
@sannegovaert since your task list refers to the implementation in the R package camtrapdp, I have removed your comment here and added it as https://github.com/inbo/camtrapdp/issues/75#issuecomment-2265484138

**Comment by peterdesmet** [comment]
The function [`camtrapdp::merge_camtrapdp()`](https://inbo.github.io/camtrapdp/reference/merge_camtrapdp.html) now supports this functionality. It combines properties as described above, except for:

2. No `projectID` is added to the deployments table, as that would create an invalid Camtrap DP.
5. `name` is removed.
6. `id` is removed. If it was a DOI, it is added to `relatedIdentifiers`.
8. `title` is removed
18. Rather than creating an array with two projects - which would be an invalid Camtrap DP - the project information is combined. This works quite well. For `samplingDesign` only a single value is allowed, so we keep the first one (and will warn if a second different one is removed).
25. Additional resources of both datasets are kept, and given unique names if necessary.
26. Additional properties of the first dataset are retained.

The aim of the function is to **create a valid Camtrap DP**. It's main use case is to combine data for a meta-analysis. It can also be used however to combine subprojects into a single dataset for publication. That dataset is then considered to describe the overarching project and the user is expected to complete/correct metadata before publication. For Camtrap DP as a standard, **we retain the paradigm that one dataset = one project**.
