### ISSUE TITLE
Error when trying to read .json in R (Agouti)

### ISSUE THREAD

**Issue by katzikatz** [tdwg/camtrap-dp#388]
Hi there,
I am looking for some help, I am experiencing an error when I am trying to read the file in R Studio after unzipping the Agouti Download.
![289670-66E40A00-3-782FAF00](https://github.com/user-attachments/assets/b19e49a3-e8f0-4c83-9977-1260f25e9e46)
I have looked at the .csv separately and they look fine, I am not sure where the problem lies. Can someone help? Thank you so much!

kind regards,
Katzi

**Comment by peterdesmet** [comment]
Hi @katzikatz, your issue is related to the camtraptor R package, so I have posted it over there and close it here (this repository is about the Camtrap DP standard itself).

Please see https://github.com/inbo/camtraptor/issues/334

**Comment by katzikatz** [comment]
thank you so much! sorry
