### ISSUE TITLE
How to express different events/sequences in a long video?

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#39]
In GitLab by @peterdesmet on Sep 2, 2020, 20:20

Ferdinando Urbano presented an interesting use case: how to express a long video being chunked into different events/sequences?

I think this can be done by repeating the `media_id` but associating different `event_id`s:

media_id | event_id | timestamp | file
--- | --- |--- | ---
1 | A | 2020-09-02T10:00:00 | video_1.mp4
1 | B | 2020-09-02T10:05:00 | video_1.mp4
1 | C | 2020-09-02T10:10:00 | video_1.mp4

I.e. the opposite of where `event_id` generally groups different `media_id`s. To know what sections of the video are chunked, the timestamps should be different, but I'm not entirely sure if that fits the definition of:

> Date and time when the multimedia file was recorded

Other suggestions?

**Comment by peterdesmet** [comment]
@feurbano This is now supported with the single observation table (#314). Assume a video with length T0-T3. It can be chunked in the observation table as:

mediaID | eventStart | eventEnd
--- | --- | ---
video1 | T0 | T1
video1 | T1 | T2
video1 | T2 | T3
