### ISSUE TITLE
How to describe target species?

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#41]
In GitLab by @peterdesmet on Sep 8, 2020, 14:04

_This issue pivoted to a discussion on how to indicate target species_

The current definition of taxonomic coverage is:

> Taxonomic coverage for this data package. It is based on a set of unique values from `scientific_name` field in `observations.csv` table.

Could this be broadened to allow the inclusion of species that were available for determination (e.g. in a project defined species list) or were considered target species, **but did not result in observations**? Or should we consider another way to allow the inclusion of target species?

**Comment by niconoe** [comment]
In GitLab by @kbubnicki on Nov 30, 2020, 11:09

If I understand you correctly you would like to preserve the information about "real zeros" i.e. not recorded species confirmed before to be present in the study area, right? Very good point I would say, but I am not convinced that this should be mixed with the idea of `taxonomic` coverage. Mainly because this can be confusing for people searching for datasets containing images/videos of particular species or for algorithms doing an automatic data aggregation/harmonization etc For this reason I would not mix these two things. I think this needs more thinking and probably `community:feedback`?

**Comment by niconoe** [comment]
In GitLab by @peterdesmet on Nov 30, 2020, 16:30

Ok to keep taxonomic coverage to only those taxa that are included in dataset. :+1: Target species can be mentioned in dataset description anyway. Fine to close this issue.

**Comment by niconoe** [comment]
In GitLab by @kbubnicki on Nov 30, 2020, 17:48

What about not closing this but leaving marked as `community:feedback`? I see this as an interesting topic in general.

**Comment by niconoe** [comment]
In GitLab by @peterdesmet on Nov 30, 2020, 17:51

Ok, but best to update the title of this issue then

**Comment by niconoe** [comment]
In GitLab by @peterdesmet on Dec 1, 2020, 12:55

changed the description

**Comment by niconoe** [comment]
In GitLab by @peterdesmet on Dec 1, 2020, 12:55

changed title from **{-Broaden scope of taxonomic coverage to include target species-}** to **{+How to describe target species?+}**

**Comment by niconoe** [comment]
In GitLab by @kbubnicki on Dec 1, 2020, 15:09

Perfect!

**Comment by peterdesmet** [comment]
Picking this one up again. Taxonomic scope is intended to list **all** species in the observations, but that doesn't really tell us much regarding:
1. What species were targeted (if any) and which ones were by catch
2. To what level classifications were made (only target species, sex, life stages, etc.).

I think the latter one is quite difficult to standardize _and_ for publishers to assess at project level. The target species however could be indicated by adding an optional property `target=TRUE` to taxa in taxonomic coverage. The R package camtraptor could then e.g. include a `target` column to the observations based on the taxonomic coverage, just like it already does for vernacular names (ping @damianooldoni).

```json
{
      "taxonID": "RQPW",
      "taxonIDReference": "https://www.checklistbank.org/dataset/3LR",
      "scientificName": "Castor fiber",
      "taxonRank": "species",
      "target": true, <--
      "vernacularNames": {
        "en": "Eurasian beaver",
        "nl": "bever"
      }
    },
    {
      "taxonID": "6MB3T",
      "taxonIDReference": "https://www.checklistbank.org/dataset/3LR",
      "scientificName": "Homo sapiens",
      "taxonRank": "species",
      "target": false, <--
      "vernacularNames": {
        "en": "human",
        "nl": "mens"
      }
    },
```

**Comment by damianooldoni** [comment]
I agree with you @peterdesmet: it's something to be specified in the taxonomic coverage (metadata) and can be indeed picked up by a package like camtraptor while reading this information from the camtrap datapackage. Indeed, something we do already with some other fields like vernacular names.

**Comment by peterdesmet** [comment]
Discussed with @kbubnicki. The problem with adding a `target=TRUE` is twofold:

- It only addresses a small aspect of sampling intend. There's also the spatial and temporal intend and other things that are best described in separate terms borrowed from Humboldt Extension (see #276)
- What do you do when a `target=TRUE` taxon was not observed. Do you add it to `taxonomic` scope? In that case, your taxonomic scope no longer describes the data (it's bigger than the data).

When there is a demand for it, it will likely be better to describe `targetTaxa` in a separate term, listing all target taxa (whether observed or not). That term will then align well with https://tdwg.github.io/hc/terms/#hc:targetTaxonomicScope. For now (1.0), we refer to the free text project `description` to indicate target taxa.
