### ISSUE TITLE
Add cam_direction to deployment

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#42]
In GitLab by @peterdesmet on Sep 8, 2020, 18:41

_Note: this was suggested in the 2020-09-08 EUROMAMMAL technical call_

In addition to `cam_height` and `cam_angle`, it would be useful to know the **camera trap orientation/direction** (wind direction).

The EUROMAMMAL table suggests `north; west; south; east`, but I would suggest a (decimal) degrees from north (e.g. south = 180). The same is used for [heading](http://vocab.nerc.ac.uk/collection/MVB/current/MVB000129/) in Movebank.

My proposal:

```json
{
  "name": "orientation",
  "type": "number", # Or integer
  "format": "default",
  "description": "The direction of the camera in decimal degrees clockwise from north (0 = north, 90 = east, 180 = south, 270 = west).", # Or degrees
  "example": "311.2", # Or integer
  "constraints": {
    "required": false,
    "minimum": 0,
    "maximum": 360
   }
}

```

**Comment by niconoe** [comment]
In GitLab by @peterdesmet on Sep 23, 2020, 10:01

This term is also suggested by @Tim-Hofmeester in #55.

**Comment by niconoe** [comment]
In GitLab by @Tim-Hofmeester on Sep 23, 2020, 12:50

sorry missed that it was already here!

**Comment by peterdesmet** [comment]
This is implemented in https://tdwg.github.io/camtrap-dp/data/#deployments.cameraheading
