### ISSUE TITLE
Add cam_firmware to deployment

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#43]
In GitLab by @peterdesmet on Sep 8, 2020, 18:44

_Note: this was suggested in the 2020-09-08 EUROMAMMAL technical call_

For some projects it might be useful to know the firmware of the camera that was used. This needs further community feedback before we can decide if and how this should be part of the standard.

**Comment by niconoe** [comment]
In GitLab by @peterdesmet on Sep 8, 2020, 18:47

changed the description

**Comment by kbubnicki** [comment]
This feature could be useful, but there have not been many requests or demonstrated use cases for it since 2021. Therefore, I suggest closing this issue. This particular information could be stored in the new field `cameraSettings` suggested in PR #389.
