### ISSUE TITLE
Add distance to observations

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#47]
In GitLab by @peterdesmet on Sep 8, 2020, 18:55

_Note: this was suggested in the 2020-09-08 EUROMAMMAL technical call_

Some studies know or have calculated the distance of the observed animal from the camera. Since this can differ from species to species, it is not a property of the deployment, but of the observation. It might be useful to add this term to observations, expressed in meters or centimeters.

**Comment by niconoe** [comment]
In GitLab by @Tim-Hofmeester on Sep 22, 2020, 11:47

Hej! I am joining the discussion for the first time, so still figuring out how everything works. I think adding the distance is a great idea. It would also be good to include the possibility to give an interval rather than an absolute distance and add a possibility to state which method was used to determine distance (measured in the field, using reference images with known sticks) and if the distance was at first detection or when walking through the mid line.

**Comment by niconoe** [comment]
In GitLab by @jimcasaer on Sep 22, 2020, 12:15

thanks for the nice suggestions Tim

**Comment by niconoe** [comment]
In GitLab by @peterdesmet on Sep 24, 2020, 14:29

@Tim-Hofmeester thanks for all the suggestions you made! Good to see feedback on the standard.

**Comment by peterdesmet** [comment]
This is addressed in #210.
