### ISSUE TITLE
Consider table "individual"

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#50]
In GitLab by @peterdesmet on Sep 8, 2020, 20:14

_Note: this was suggested in the 2020-09-08 EUROMAMMAL technical call_

`individual_id` in observations allows to indicate repeat viewings of individuals, but apart from the sex and the life_stage (at the time) no further information (like other tag numbers) can be provided. Information on recognizable/marked individuals that did were _not_ observed by the camera traps cannot be shared either.

To share this information, we could consider adding an extra file `individuals.csv`, where further information regarding recognizable/marked individuals can be shared. Fields could be:

- `individual_id`
- `scientific_name`
- `life_stage`: debatable since it can change over time
- `sex`: not likely to change for camera trap observed species
- `other_identifiers`: e.g. `ring_number:HR456; movebank_id:894`
- `comments`

But I think this needs further community feedback before we can decide if and how this should be part of the standard.

**Comment by peterdesmet** [comment]
Note the example dataset now includes an `individuals` resource, but only to showcase that it is possible to include non Camtrap DP resources in a Camtrap DP dataset (as long as they don't use the reserved names `deployments`, ...)

**Comment by sannegovaert** [comment]
See https://github.com/inbo/camtrapdp/pull/149

**Comment by peterdesmet** [comment]
This is now implemented in the camtrapdp R package, as a derived table from observations. There are a couple of [such tables](https://inbo.github.io/camtrapdp/reference/index.html#accessor-and-assignment-functions):

- locations(): from deployments
- taxa(): from observations + taxonomic
- events(): from observations
- **individuals(): from observations**

We won't add an individual table to the Camtrap DP model:

- There is no use case for it
- There is an easy helper function in camtrapdp to generate one from observations
- It is always possible to add a custom table

We will extend the example dataset to include individual info (see #396).
