### ISSUE TITLE
Add distance to bait_use and feature_type in deployment table

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#54]
In GitLab by @Tim-Hofmeester on Sep 22, 2020, 12:34

I think it would be informative to add a (optional) term for the distance between camera and a potential bait/lure or feature. For example, if the method is standardized and lure is positioned at 3m from the camera, that might be good to know as others might have standardized it at 5m and that might influence detection of especially smaller species. Same counts for things like roads or trails.

**Comment by niconoe** [comment]
In GitLab by @kbubnicki on Sep 26, 2020, 13:04

Good suggestion! For this kind of issues we have a dedicated label `community:feedback`. The idea is that when we have the first complete draft of the schema we present it to a broader community and include issues like this one to collect feedback (voting?) and to learn how useful it would be to have this information in the schema.

**Comment by kbubnicki** [comment]
@Tim-Hofmeester, is this still a relevant topic in your opinion? Does it make sense to add a new field? It is difficult for me to assess how common this use case is, as I have no real experience using baits in my camera trapping projects. Maybe one can use `deploymentTags` to store this design-specific information, e.g., `distanceBait:3`.

**Comment by Tim-Hofmeester** [comment]
I definitely think it is important information, but I don't think it needs a new field if there is a clear way of how to report this type of information. The suggestion to use deploymentTags and distanceBait would work for me.

**Comment by peterdesmet** [comment]
Thanks @Tim-Hofmeester, will close this issue then.
