### ISSUE TITLE
Add habitat_modification to deployment table

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#56]
In GitLab by @Tim-Hofmeester on Sep 22, 2020, 12:37

Some studies modify the habitat in front of camera traps, e.g., by clearing all vegetation in front of the camera trap up to 3-5m. As this might influence detection of different species it might be informative to add this term to the deployment info.

**Comment by kbubnicki** [comment]
@Tim-Hofmeester, I'm not sure how this information could be standardized or how it differs from a very fine-scale description of the camera site habitat in general. I would suggest using some available fields to provide this information (e.g., `habitat`, `deploymentComments` in the `deployments.csv` table).

I am closing this issue now but will be happy to re-open it if there are good arguments for a more in-depth discussion on this topic!

**Comment by Tim-Hofmeester** [comment]
Agree that it would be difficult to standardize and can be given in deploymentComments. So happy with that solution.
