### ISSUE TITLE
New term for deployments: camera_detection_distance

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#6]
In GitLab by @peterdesmet on Aug 10, 2020, 16:30

In Agouti, deployments have a field `detectionDistance`. It is not often populated, but maybe it could be added to the deployments schema as `camera_detection_distance`, indicating up to which max distance the camera will trigger.

**Comment by niconoe** [comment]
In GitLab by @kbubnicki on Aug 28, 2020, 13:09

I think this is exactly where we need the community feedback (kind of voting?). Personally, I would say it depends on what kind of a detection distance we are talking about: provided by a manufacturer (then we have [`cam_model`](https://gitlab.com/oscf/camtrap-package-schemas/-/blob/master/deployments-table-schema.json#L99)) or kind of an effective detection distance modeled for particular study/site etc?

**Comment by niconoe** [comment]
In GitLab by @kbubnicki on Aug 28, 2020, 13:12

I have just added the new label: `community:feedback`; Maybe we can use it to mark this kind of issues?

**Comment by niconoe** [comment]
In GitLab by @peterdesmet on Aug 28, 2020, 13:15

Good idea, just attached it to this issue.

**Comment by niconoe** [comment]
In GitLab by @peterdesmet on Sep 28, 2020, 18:46

changed title from **New term for deployments: cam_detection_distance** to **New term for deployments: cam{+era+}_detection_distance**

**Comment by niconoe** [comment]
In GitLab by @peterdesmet on Sep 28, 2020, 18:46

changed the description

**Comment by peterdesmet** [comment]
`detection_distance` was also suggested in #133, so this issue is added to milestone 1. With the term we want to express the "maximum detection distance in meters".

- [ ] I assume this could be one provided by the manufacturer or measured by the researcher?
- [ ] If we allow the latter (measured by researcher), I would call it `detection_distance` rather than `camera_detection_distance`.

@yliefting we have this term in Agouti, what does it express?
@Tim-Hofmeester @jimcasaer what is need from the user perspective?

**Comment by Tim-Hofmeester** [comment]
I think most projects (that I know of) that measure this parameter measure the maximum distance at which the camera detects a human when setting up the camera. I don't think manufacturers specify a maximum detection distance for the PIR sensor (but I might be wrong). In any case, I think the most interesting parameter that might be measured is the one measured by the researcher. The main problem though is that this distance is dependent on the surface temperature of the surrounding landscape so interpretation is only meaningful if the distances were measured under similar conditions. 

The term detection_distance would be fine. As long as the description clearly states that it is the maximum distance at which a human could be identified at the time of deploying the camera (as that is the easiest thing to measure in a standardized way and is what is measured by e.g., the group of Roland Kays and my group.

It often helps to correct for this parameter in the analytics phase as deployments/locations might differ a lot in 'how far the camera can see' and thus how far away animals might potentially be detected. Especially in studies with a mix of open and more dense vegetation or studies in places with very rugged terrain. It can also be used as a covariate to estimate camera and species specific effective detection distances.

**Comment by peterdesmet** [comment]
Thanks @Tim-Hofmeester that is useful feedback!

**Comment by peterdesmet** [comment]
This term was also suggested in the batch of changes at #133: add to deployments as maximum detection distance in meters

**Comment by peterdesmet** [comment]
Draft suggestion by @ben-norton:

> Furthest linear distance the camera used in deployment_name detects in a test by the person who set up the camera. Will vary depending on camera make and model, as well as the environment the camera is facing at latitude, longitude

**Comment by ben-norton** [comment]
> Draft suggestion by @ben-norton:
> 
> > Furthest linear distance the camera used in deployment_name detects in a test by the person who set up the camera. Will vary depending on camera make and model, as well as the environment the camera is facing at latitude, longitude

Proposed revision: The furthest linear distance an entity is detected by a camera during a single deployment as measured at the deployment location during setup. 

Detection distance does depend on make/model and local environment, but that's implied. I don't think there is a need to mention it. The local topography and features are probably the most important factor when measuring detection distance, but again I don't think it's necessary to include this in the definition. 
I am aware of at least two active areas of research that include the measurement of movement activity, which requires a known detection distance. Also, detection distance belongs to a suite of best practices to optimize data capture rates. For example, detection distance beyond a certain number may result in an excessive number of blank acquisitions and possible errors.

**Comment by peterdesmet** [comment]
@ben-norton can we simplify that definition to:

> Furthest distance at which the camera detected a human during deployment setup.

- Drops `linear`, I don't think its necessary to specify that.
- `is` could also be `was`?
- `entity` is more correct, but cf. https://github.com/tdwg/camtrap-dp/issues/6#issuecomment-877120071 humans are the most often used entity to measure that. Writing `human` leaves less room for interpretation regarding how big that entity should be.
- `by a camera during a single deployment as measured at the deployment location during setup` -> shortened
