### ISSUE TITLE
Initiate datapackage.json

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#65]
In GitLab by @peterdesmet on Nov 4, 2020, 10:58

This repository contains the **templates** for the metadata (in [camtrap-package-profile.json](https://gitlab.com/oscf/camtrap-dp/-/blob/master/camtrap-package-profile.json)) and resources (the 3 table schemas), but doesn't provide a ready-to-adapt `datapackage.json` file. A lot of heavy-lifting is therefore to be done by users, data publisher or developers. I think it would be useful to create this (with a script) for each release or at least have this functionality in https://gitlab.com/oscf/camtrap-package. @kbubnicki?

**Comment by peterdesmet** [comment]
Revisiting this. Now that we have automated scripts, this would be useful to do on a merge to `main`. @niconoe would you be up for this?

**Comment by niconoe** [comment]
So the idea is that each time the standard is changed, a `datapackage.json` file is generated that an end user can simply copy/paste along a bunch of CSV files, and that would give a valid Camtrap DP package up to the current spec?

Sounds like a great idea, I'd be happy to help. About versioning: I guess the generated `datapackage.json` would have some version information that allows to pinpoint exactly which version of the standard (camtrap-package-profile.json + 3 table schemas) is actually in use in the Camtrap DP package?

**Comment by peterdesmet** [comment]
Almost:

> So the idea is that each time the standard is changed, a datapackage.json file is generated that an end user can simply copy/paste along a bunch of CSV files **and adapt**. **Some terms would need to be populated by the user in order to make it** a valid Camtrap DP package up to the current spec.

**Comment by peterdesmet** [comment]
I'm not sure this autogenerated `datapackage.json` can be entirely created using the current files in the repository. I think more information (like a template) is needed, which we then also have to maintain. 😕
