### ISSUE TITLE
Are plants ever annotated on camtrap images?

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#67]
In GitLab by @peterdesmet on Nov 24, 2020, 12:15

Question for the community watching this repository:

> Are plants (or other non-animals) ever annotated on camera trap images?

I'm asking because in the context of translating camtrap-dp data to Darwin Core (generically, not for a specific dataset), and I set `kingdom` to `Animalia`, but that might be assuming too much.

**Comment by niconoe** [comment]
In GitLab by @PietrH on Jan 6, 2021, 09:19

Hi Peter, we currently don't annotate plants for the botanical garden camera trap dataset, but we have thought about it. I can see a usecase especially when I would want to capture an interaction, a hypothetical example: Imagine I observe a magpie eating a fern, that would be unexpected, and I would want to capture this, apart from the difficulty of capturing species interactions in DwC in general, I would want to have an observation for both species within my occurrence dataset. 

However, currently we don't have any plants in the dataset, and altough it's technically possible for citizen scientists to annotate them on DoeDat, the question we ask is "what animals can you see in the image", so kingdom Animalia might be a safe choice after all. How difficult would this be to change in the future if need be?

**Comment by niconoe** [comment]
In GitLab by @peterdesmet on Jan 6, 2021, 11:11

Thanks @PietrH, that is what I thought: even though it is perfectly possible to annotate plants, the interfaces will hint at animals as that is by far the biggest use case (@ anyone let me know if you have annotated plants).

In camtrap-dp, the word [`animal`](https://gitlab.com/search?utf8=%E2%9C%93&search=animal&group_id=&project_id=17818184&scope=&search_code=true&snippets=false&repository_ref=development&nav_source=navbar) is mentioned in two places. All other instances talk about `observed individual(s)`.

- `profile:**animal**_types`: indicates if the dataset contains unmarked and/or marked animals. Seems ok to name it as such: plants are not marked and the dataset will very likely also contain animals. A name such as `species_types` would be more confusing.
- `observation_type:**animal**`. This flag is to be understandable from an AI point of view and it is used to filter species observations from non-species observations. Systems (like Agouti) will export any observation with a non-human scientific name (animal or plant) as an `observation_type:animal`. Since the use case for plants is so small, I think that is still better then renaming it to `observation_type:species` (since AI will specifically look for **animals**) or adding a `observation_type:plants` (since users then need to search for two flags). @yliefting @kbubnicki any thoughts on this?


In Darwin Core, with the use case of plants so small, it seems better to assume kingdom `Animalia` then to leave that field empty.

**Comment by ben-norton** [comment]
1. As a matter of best practices, I'd prefer the removal of Animalia as the default value. However, I think this an exception.
2. Camera Traps aren't used to identify plants. It's a use case. 
3. Plants and animals are described differently. Opening this up to plants may require another level of complexity to observations that isn't necessary for the purposes of camera traps.
4. Over a single deployment, the plants n the field of view won't change (aside from seasonal foliage or minor disturbances). Therefore, you could move this to a description field in deployments if necessary.

**Comment by peterdesmet** [comment]
Ok, in the suggested [Darwin Core mapping](https://github.com/tdwg/dwc-for-biologging/blob/de81e71733e3cf17b1b45f5938c50ed53adf3672/derived/camtrap-dp/sql/dwc_occurrence.sql#L259-L260), I will leave `Animalia` as mapping for kingdom. I will also leave [all four mentions](https://github.com/tdwg/camtrap-dp/search?q=animal) of the word `animal` in camtrap-dp, as it is the biggest use case and easier to understand. In the taxonomy, we talk about `taxa` and `species`.

Closing issue.
