### ISSUE TITLE
Indicate % of classified records in metadata

### ISSUE THREAD

**Issue by niconoe** [tdwg/camtrap-dp#74]
In GitLab by @peterdesmet on Dec 14, 2020, 14:33

As mentioned by @kbubnicki [here](https://gitlab.com/oscf/camtrap-dp/-/issues/73#note_466143708): 

> Then I am directly thinking about adding some (metadata) metric at a data-package level providing the information about % of observations that are already classified?

**Comment by niconoe** [comment]
In GitLab by @peterdesmet on Dec 14, 2020, 14:36

Would this be the % of observations NOT marked as `unclassified`? Or the number of unique `sequence_id`/`media_id` marked as such?

And is it in comparison with all media in the project or the data package? Note that some exports will not include unclassified observations.

**Comment by peterdesmet** [comment]
Discussed with @kbubnicki: this information can be derived from the data and should not be expressed in the metadata.
